// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Music.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20251212144741_Satina")]
    partial class Satina
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.HasKey("GenreId", "AlbumId")
                        .HasName("AlbumGenres_pkey");

                    b.HasIndex("AlbumId");

                    b.ToTable("AlbumGenres", (string)null);
                });

            modelBuilder.Entity("ArtistGenre", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("ArtistId", "GenreId")
                        .HasName("ArtistGenre_pkey");

                    b.HasIndex("GenreId");

                    b.ToTable("ArtistGenre", (string)null);
                });

            modelBuilder.Entity("Music.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("integer");

                    b.HasKey("AlbumId")
                        .HasName("Albums_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Music.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("ArtistId")
                        .HasName("Artists_pkey");

                    b.HasIndex("CountryId");

                    b.HasIndex(new[] { "ArtistName" }, "Artists_ArtistName_key")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Music.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId")
                        .HasName("Countries_pkey");

                    b.HasIndex(new[] { "CountryName" }, "Countries_CountryName_key")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Music.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId")
                        .HasName("Genres_pkey");

                    b.HasIndex(new[] { "GenreName" }, "Genres_GenreName_key")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Music.Models.LoginAttempt", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoginId"));

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginId")
                        .HasName("LoginAttempts_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("Music.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistId"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId")
                        .HasName("Playlists_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Music.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId")
                        .HasName("Roles_pkey");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Music.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubscriptionId")
                        .HasName("Subscriptions_pkey");

                    b.HasIndex(new[] { "SubscriptionName" }, "Subscriptions_SubscriptionName_key")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Music.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId")
                        .HasName("Tag_pkey");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("Music.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int>("Bitrate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrackId")
                        .HasName("Tracks_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex(new[] { "FilePath" }, "Tracks_FilePath_key")
                        .IsUnique();

                    b.HasIndex(new[] { "TrackName" }, "Tracks_TrackName_key")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Music.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("Users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex(new[] { "Email" }, "Users_Email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserLogin" }, "Users_UserLogin_key")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Music.Models.UserPlaylistSubscription", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubscriptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "PlaylistId")
                        .HasName("UserPlaylistSubscriptions_pkey");

                    b.HasIndex("PlaylistId");

                    b.ToTable("UserPlaylistSubscriptions");
                });

            modelBuilder.Entity("PlaylistTag", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "TagId")
                        .HasName("PlaylistTags_pkey");

                    b.HasIndex("TagId");

                    b.ToTable("PlaylistTags", (string)null);
                });

            modelBuilder.Entity("PlaylistTrack", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "TrackId")
                        .HasName("PlaylistTracks_pkey");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTracks", (string)null);
                });

            modelBuilder.Entity("TrackArtist", b =>
                {
                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.HasKey("TrackId", "ArtistId")
                        .HasName("TrackArtist_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtist", (string)null);
                });

            modelBuilder.Entity("TrackGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("GenreId", "TrackId")
                        .HasName("TrackGenres_pkey");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackGenres", (string)null);
                });

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.HasOne("Music.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("AlbumGenres_AlbumId_fkey");

                    b.HasOne("Music.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("AlbumGenres_GenreId_fkey");
                });

            modelBuilder.Entity("ArtistGenre", b =>
                {
                    b.HasOne("Music.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("ArtistGenre_ArtistId_fkey");

                    b.HasOne("Music.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("ArtistGenre_GenreId_fkey");
                });

            modelBuilder.Entity("Music.Models.Album", b =>
                {
                    b.HasOne("Music.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("Albums_ArtistId_fkey");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Music.Models.Artist", b =>
                {
                    b.HasOne("Music.Models.Country", "Country")
                        .WithMany("Artists")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("Artists_CountryId_fkey");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Music.Models.LoginAttempt", b =>
                {
                    b.HasOne("Music.Models.User", "User")
                        .WithMany("LoginAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("LoginAttempts_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Music.Models.Playlist", b =>
                {
                    b.HasOne("Music.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Playlists_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Music.Models.Track", b =>
                {
                    b.HasOne("Music.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("Tracks_AlbumId_fkey");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Music.Models.User", b =>
                {
                    b.HasOne("Music.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("Users_RoleId_fkey");

                    b.HasOne("Music.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("Users_SubscriptionId_fkey");

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Music.Models.UserPlaylistSubscription", b =>
                {
                    b.HasOne("Music.Models.Playlist", "Playlist")
                        .WithMany("UserPlaylistSubscriptions")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("UserPlaylistSubscriptions_PlaylistId_fkey");

                    b.HasOne("Music.Models.User", "User")
                        .WithMany("UserPlaylistSubscriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("UserPlaylistSubscriptions_UserId_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaylistTag", b =>
                {
                    b.HasOne("Music.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("PlaylistTags_PlaylistId_fkey");

                    b.HasOne("Music.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("PlaylistTags_TagId_fkey");
                });

            modelBuilder.Entity("PlaylistTrack", b =>
                {
                    b.HasOne("Music.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("PlaylistTracks_PlaylistId_fkey");

                    b.HasOne("Music.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("PlaylistTracks_TrackId_fkey");
                });

            modelBuilder.Entity("TrackArtist", b =>
                {
                    b.HasOne("Music.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("TrackArtist_ArtistId_fkey");

                    b.HasOne("Music.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("TrackArtist_TrackId_fkey");
                });

            modelBuilder.Entity("TrackGenre", b =>
                {
                    b.HasOne("Music.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("TrackGenres_GenreId_fkey");

                    b.HasOne("Music.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("TrackGenres_TrackId_fkey");
                });

            modelBuilder.Entity("Music.Models.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Music.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Music.Models.Country", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Music.Models.Playlist", b =>
                {
                    b.Navigation("UserPlaylistSubscriptions");
                });

            modelBuilder.Entity("Music.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Music.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Music.Models.User", b =>
                {
                    b.Navigation("LoginAttempts");

                    b.Navigation("Playlists");

                    b.Navigation("UserPlaylistSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
