<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\covers\As Alive As You Need Me To Be.jpg" />
    <None Remove="Resources\covers\Baby.jpg" />
    <None Remove="Resources\covers\Barbara Barbara, we face a shining future.jpg" />
    <None Remove="Resources\covers\Bloodline %28Bonus Tracks%29.jpg" />
    <None Remove="Resources\covers\Breed %28feat. REEBZ%29.jpg" />
    <None Remove="Resources\icon.ico" />
    <None Remove="Resources\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\covers\As Alive As You Need Me To Be.jpg" />
    <Resource Include="Resources\covers\Baby.jpg" />
    <Resource Include="Resources\covers\Barbara Barbara, we face a shining future.jpg" />
    <Resource Include="Resources\covers\Bloodline (Bonus Tracks).jpg" />
    <Resource Include="Resources\covers\Breed (feat. REEBZ).jpg" />
    <Resource Include="Resources\icon.ico" />
    <Resource Include="Resources\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Classes\" />
  </ItemGroup>

</Project>
