// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spotify_wpf.Context;

#nullable disable

namespace Spotify_wpf.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20251127091900_music")]
    partial class music
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spotify_wpf.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Album_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("Artist_Id");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("integer");

                    b.HasKey("AlbumId")
                        .HasName("Album_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.AlbumGenre", b =>
                {
                    b.Property<int>("AlbumGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Album_Genre_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumGenreId"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("Album_Id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("Genre_Id");

                    b.HasKey("AlbumGenreId")
                        .HasName("Album_Genre_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("Album_Genre", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.AlbumTrack", b =>
                {
                    b.Property<int>("AlbumTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Album_Track_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumTrackId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("Album_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_Id");

                    b.HasKey("AlbumTrackId")
                        .HasName("Album_Track_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("TrackId");

                    b.ToTable("Album_Track", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Artist_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Artist_Name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YearsActivity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Years_Activity");

                    b.HasKey("ArtistId")
                        .HasName("Artist_pkey");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Genre_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Genre_Name");

                    b.HasKey("GenreId")
                        .HasName("Genre_pkey");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.GenreArtist", b =>
                {
                    b.Property<int>("GenreArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("GenreArtist_Id")
                        .HasDefaultValueSql("nextval('\"AlbumArtist_AlbumArtist_Id_seq\"'::regclass)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("Artist_Id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("Genre_Id");

                    b.HasKey("GenreArtistId")
                        .HasName("AlbumArtist_pkey");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Genre_Artist", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.GenreTrack", b =>
                {
                    b.Property<int>("GenreTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Genre_Track_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreTrackId"));

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("Genre_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_Id");

                    b.HasKey("GenreTrackId")
                        .HasName("Genre_Track_pkey");

                    b.HasIndex("GenreId");

                    b.HasIndex("TrackId");

                    b.ToTable("Genre_Track", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.PlayListTrack", b =>
                {
                    b.Property<int>("PlayListTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PlayList_Track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayListTrackId"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_Id");

                    b.HasKey("PlayListTrackId")
                        .HasName("PlayList_Track_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlayList_Track", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Playlist", b =>
                {
                    b.Property<int>("PlayListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PlayList_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayListId"));

                    b.Property<DateOnly>("DataCreate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Playlist_Name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("PlayListId")
                        .HasName("Playlists_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Spotify_wpf.Models.PlaylistUser", b =>
                {
                    b.Property<int>("PlaylistUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_User_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistUserId"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_Id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("PlaylistUserId")
                        .HasName("Playlist_User_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("Playlist_User", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Role_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Subscription_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("Subscription1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Subscription");

                    b.HasKey("SubscriptionId")
                        .HasName("Subscription_pkey");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Tag", b =>
                {
                    b.Property<int>("TagsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Tags_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagsId"));

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tags_Name");

                    b.HasKey("TagsId")
                        .HasName("Tags_pkey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Spotify_wpf.Models.TagsPlaylist", b =>
                {
                    b.Property<int>("TagsPlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Tags_Playlist_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagsPlaylistId"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_Id");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer")
                        .HasColumnName("Tags_Id");

                    b.HasKey("TagsPlaylistId")
                        .HasName("Tags_Playlist_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TagsId");

                    b.ToTable("Tags_Playlist", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Track_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackId"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("Album_Id");

                    b.Property<int>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time without time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Playcount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrackId")
                        .HasName("Track_pkey");

                    b.HasIndex("AlbumId");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.TrackArtist", b =>
                {
                    b.Property<int>("TrackArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrackArtist_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackArtistId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("Artist_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_Id");

                    b.HasKey("TrackArtistId")
                        .HasName("TrackArtist_pkey");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackArtist", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastLogin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Role_Id");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("Subscription_Id");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_Login");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_Password");

                    b.HasKey("UserId")
                        .HasName("User_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Spotify_wpf.Models.Album", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("album_artist_fk");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Spotify_wpf.Models.AlbumGenre", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Album", "Album")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("Album_Genre_Album_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Genre", "Genre")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("Album_Genre_Genre_Id_fkey");

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Spotify_wpf.Models.AlbumTrack", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Album", "Album")
                        .WithMany("AlbumTracks")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("Album_Track_Album_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Track", "Track")
                        .WithMany("AlbumTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("Album_Track_Track_Id_fkey");

                    b.Navigation("Album");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Spotify_wpf.Models.GenreArtist", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Artist", "Artist")
                        .WithMany("GenreArtists")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("AlbumArtist_Artist_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Genre", "Genre")
                        .WithMany("GenreArtists")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("genre_artist_genre_fk");

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Spotify_wpf.Models.GenreTrack", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Genre", "Genre")
                        .WithMany("GenreTracks")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("Genre_Track_Genre_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Track", "Track")
                        .WithMany("GenreTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("Genre_Track_Track_Id_fkey");

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Spotify_wpf.Models.PlayListTrack", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Playlist", "Playlist")
                        .WithMany("PlayListTracks")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("PlayList_Track_Playlist_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Track", "Track")
                        .WithMany("PlayListTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("PlayList_Track_Track_Id_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Playlist", b =>
                {
                    b.HasOne("Spotify_wpf.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Playlists_User_Id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spotify_wpf.Models.PlaylistUser", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Playlist", "Playlist")
                        .WithMany("PlaylistUsers")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("Playlist_User_Playlist_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.User", "User")
                        .WithMany("PlaylistUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Playlist_User_User_Id_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spotify_wpf.Models.TagsPlaylist", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Playlist", "Playlist")
                        .WithMany("TagsPlaylists")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("Tags_Playlist_Playlist_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Tag", "Tags")
                        .WithMany("TagsPlaylists")
                        .HasForeignKey("TagsId")
                        .IsRequired()
                        .HasConstraintName("Tags_Playlist_Tags_Id_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Track", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("track_album_fk");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Spotify_wpf.Models.TrackArtist", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Artist", "Artist")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("trackartist_artist_fk");

                    b.HasOne("Spotify_wpf.Models.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("trackartist_track_fk");

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Spotify_wpf.Models.User", b =>
                {
                    b.HasOne("Spotify_wpf.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("User_Role_Id_fkey");

                    b.HasOne("Spotify_wpf.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("User_Subscription_Id_fkey");

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Album", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("AlbumTracks");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("GenreArtists");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Genre", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("GenreArtists");

                    b.Navigation("GenreTracks");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Playlist", b =>
                {
                    b.Navigation("PlayListTracks");

                    b.Navigation("PlaylistUsers");

                    b.Navigation("TagsPlaylists");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Tag", b =>
                {
                    b.Navigation("TagsPlaylists");
                });

            modelBuilder.Entity("Spotify_wpf.Models.Track", b =>
                {
                    b.Navigation("AlbumTracks");

                    b.Navigation("GenreTracks");

                    b.Navigation("PlayListTracks");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("Spotify_wpf.Models.User", b =>
                {
                    b.Navigation("PlaylistUsers");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
