// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotApp_wpf.Context;

#nullable disable

namespace SpotApp_wpf.Migrations
{
    [DbContext(typeof(SpotifyContext))]
    [Migration("20251127092004_spotifydb1")]
    partial class spotifydb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotApp_wpf.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Album_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("Artist_id");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("TotalDuration")
                        .HasColumnType("time without time zone");

                    b.HasKey("AlbumId")
                        .HasName("Album_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Artist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YearsActive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId")
                        .HasName("Artists_pkey");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.ArtistsInTrack", b =>
                {
                    b.Property<int>("AiTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AiT_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AiTId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("Artist_id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_id");

                    b.HasKey("AiTId")
                        .HasName("Artists_in_Tracks_pkey");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("Artists_in_Tracks", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.GenersInTrack", b =>
                {
                    b.Property<int>("GiTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("GiT_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GiTId"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("Genre_id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_id");

                    b.HasKey("GiTId")
                        .HasName("Geners_in_Tracks_pkey");

                    b.HasIndex("GenreId");

                    b.HasIndex("TrackId");

                    b.ToTable("Geners_in_Tracks", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreTittle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Genre_tittle");

                    b.HasKey("GenreId")
                        .HasName("Genres_pkey");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.GenresInAlbum", b =>
                {
                    b.Property<int>("GiAlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("GiAl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GiAlId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("Album_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("Genre_id");

                    b.HasKey("GiAlId")
                        .HasName("Genres_in_Albums_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("Genres_in_Albums", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.GenresInArtist", b =>
                {
                    b.Property<int>("GiAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("GiA_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GiAId"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("Artist_id");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("Genre_id");

                    b.HasKey("GiAId")
                        .HasName("Genres_in_Artists_pkey");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Genres_in_Artists", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistId"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_id");

                    b.HasKey("PlaylistId")
                        .HasName("Playlists_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role_name");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Subscription_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("SubscriptionTittle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Subscription_tittle");

                    b.HasKey("SubscriptionId")
                        .HasName("Subscription_pkey");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagTittle")
                        .HasColumnType("text")
                        .HasColumnName("Tag_tittle");

                    b.HasKey("TagId")
                        .HasName("Tags_pkey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.TagsInPlaylist", b =>
                {
                    b.Property<int>("TiPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TiP_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TiPId"));

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("Tag_id");

                    b.HasKey("TiPId")
                        .HasName("Tags_in_Playlists_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TagId");

                    b.ToTable("Tags_in_Playlists", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackId"));

                    b.Property<string>("AlbumCoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("Album_id");

                    b.Property<int>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time without time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrackId")
                        .HasName("Track_pkey");

                    b.HasIndex("AlbumId");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.TracksInAlbum", b =>
                {
                    b.Property<int>("TiAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TiA_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TiAId"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("Album_id");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_id");

                    b.HasKey("TiAId")
                        .HasName("Tracks_in_Albums_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("TrackId");

                    b.ToTable("Tracks_in_Albums", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.TracksInPlaylist", b =>
                {
                    b.Property<int>("TiPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TiP_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TiPId"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("Track_id");

                    b.HasKey("TiPId")
                        .HasName("Tracks_in_Playlists_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("Tracks_in_Playlists", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("User_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Role_id");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("Subscription_id");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserId")
                        .HasName("User_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.UsersPlaylist", b =>
                {
                    b.Property<int>("UserPlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserPlaylist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPlaylistId"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("Playlist_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_id");

                    b.HasKey("UserPlaylistId")
                        .HasName("Users_Playlists_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("Users_Playlists", (string)null);
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Album", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("Album_Artist_id_fkey");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.ArtistsInTrack", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Artist", "Artist")
                        .WithMany("ArtistsInTracks")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("Artists_in_Tracks_Artist_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Track", "Track")
                        .WithMany("ArtistsInTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("Artists_in_Tracks_Track_id_fkey");

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.GenersInTrack", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Genre", "Genre")
                        .WithMany("GenersInTracks")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("Geners_in_Tracks_Genre_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Track", "Track")
                        .WithMany("GenersInTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("Geners_in_Tracks_Track_id_fkey");

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.GenresInAlbum", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Album", "Album")
                        .WithMany("GenresInAlbums")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("Genres_in_Albums_Album_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Genre", "Genre")
                        .WithMany("GenresInAlbums")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("Genres_in_Albums_Genre_id_fkey");

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.GenresInArtist", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Artist", "Artist")
                        .WithMany("GenresInArtists")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("Genres_in_Artists_Artist_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Genre", "Genre")
                        .WithMany("GenresInArtists")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("Genres_in_Artists_Genre_id_fkey");

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Playlist", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Playlists_User_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.TagsInPlaylist", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Playlist", "Playlist")
                        .WithMany("TagsInPlaylists")
                        .HasForeignKey("PlaylistId")
                        .HasConstraintName("Tags_in_Playlists_Playlist_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Tag", "Tag")
                        .WithMany("TagsInPlaylists")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("Tags_in_Playlists_Tag_id_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Track", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("Track_Album_id_fkey");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.TracksInAlbum", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Album", "Album")
                        .WithMany("TracksInAlbums")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("Tracks_in_Albums_Album_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Track", "Track")
                        .WithMany("TracksInAlbums")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("Tracks_in_Albums_Track_id_fkey");

                    b.Navigation("Album");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.TracksInPlaylist", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Playlist", "Playlist")
                        .WithMany("TracksInPlaylists")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("Tracks_in_Playlists_Playlist_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Track", "Track")
                        .WithMany("TracksInPlaylists")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("Tracks_in_Playlists_Track_id_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.User", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("User_Role_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("User_Subscription_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.UsersPlaylist", b =>
                {
                    b.HasOne("SpotApp_wpf.Models.Playlist", "Playlist")
                        .WithMany("UsersPlaylists")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("Users_Playlists_Playlist_id_fkey");

                    b.HasOne("SpotApp_wpf.Models.User", "User")
                        .WithMany("UsersPlaylists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Users_Playlists_User_id_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Album", b =>
                {
                    b.Navigation("GenresInAlbums");

                    b.Navigation("Tracks");

                    b.Navigation("TracksInAlbums");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ArtistsInTracks");

                    b.Navigation("GenresInArtists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Genre", b =>
                {
                    b.Navigation("GenersInTracks");

                    b.Navigation("GenresInAlbums");

                    b.Navigation("GenresInArtists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Playlist", b =>
                {
                    b.Navigation("TagsInPlaylists");

                    b.Navigation("TracksInPlaylists");

                    b.Navigation("UsersPlaylists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Tag", b =>
                {
                    b.Navigation("TagsInPlaylists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.Track", b =>
                {
                    b.Navigation("ArtistsInTracks");

                    b.Navigation("GenersInTracks");

                    b.Navigation("TracksInAlbums");

                    b.Navigation("TracksInPlaylists");
                });

            modelBuilder.Entity("SpotApp_wpf.Models.User", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("UsersPlaylists");
                });
#pragma warning restore 612, 618
        }
    }
}
