// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicWpf.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicWpf.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20251127103609_Music")]
    partial class Music
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicWpf.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("integer");

                    b.HasKey("AlbumId")
                        .HasName("Album_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.AlbumGenre", b =>
                {
                    b.Property<int>("AlbumGenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumGenresId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("AlbumGenresId")
                        .HasName("AlbumGenres_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("AlbumGenres");
                });

            modelBuilder.Entity("MusicWpf.Models.AlbumTrack", b =>
                {
                    b.Property<int>("AlbumTracksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumTracksId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int>("TracksId")
                        .HasColumnType("integer");

                    b.HasKey("AlbumTracksId")
                        .HasName("AlbumTracks_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("TracksId");

                    b.ToTable("AlbumTracks");
                });

            modelBuilder.Entity("MusicWpf.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YearsActive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId")
                        .HasName("Artist_pkey");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.ArtistTrack", b =>
                {
                    b.Property<int>("ArtistTracksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistTracksId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("ArtistTracksId")
                        .HasName("ArtistTracks_pkey");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("ArtistTracks");
                });

            modelBuilder.Entity("MusicWpf.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId")
                        .HasName("Genre_pkey");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.GenreArtist", b =>
                {
                    b.Property<int>("GenreArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreArtistId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("GenreArtistId")
                        .HasName("GenreArtist_pkey");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreArtist", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistId"));

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId")
                        .HasName("Playlist_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Playlist", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.PlaylistTag", b =>
                {
                    b.Property<int>("PlaylistTagsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistTagsId"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistTagsId")
                        .HasName("PlaylistTags_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TagsId");

                    b.ToTable("PlaylistTags");
                });

            modelBuilder.Entity("MusicWpf.Models.PlaylistsUser", b =>
                {
                    b.Property<int>("PlaylistsUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistsUserId"));

                    b.Property<int>("PlaylistsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistsUserId")
                        .HasName("PlaylistsUser_pkey");

                    b.HasIndex("PlaylistsId");

                    b.HasIndex("UserId");

                    b.ToTable("PlaylistsUser", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubscriptionId")
                        .HasName("Subscription_pkey");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.Tag", b =>
                {
                    b.Property<int>("TagsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagsId"));

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagsId")
                        .HasName("Tags_pkey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MusicWpf.Models.Track", b =>
                {
                    b.Property<int>("TracksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TracksId"));

                    b.Property<string>("AlbumCoverBinary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlbumCoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlbumInfo")
                        .HasColumnType("text");

                    b.Property<int>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time without time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TracksId")
                        .HasName("Tracks_pkey");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("MusicWpf.Models.TracksGenre", b =>
                {
                    b.Property<int>("TracksGenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TracksGenresId"));

                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("TracksId")
                        .HasColumnType("integer");

                    b.HasKey("TracksGenresId")
                        .HasName("TracksGenres_pkey");

                    b.HasIndex("GenresId");

                    b.HasIndex("TracksId");

                    b.ToTable("TracksGenres");
                });

            modelBuilder.Entity("MusicWpf.Models.TracksPlaylist", b =>
                {
                    b.Property<int>("TracksPlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int?>("TracksId")
                        .HasColumnType("integer");

                    b.HasKey("TracksPlaylistId")
                        .HasName("TracksPlaylist_pkey");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TracksId");

                    b.ToTable("TracksPlaylist", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastLogin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserId")
                        .HasName("User_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MusicWpf.Models.Album", b =>
                {
                    b.HasOne("MusicWpf.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("Album_ArtistId_fkey");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicWpf.Models.AlbumGenre", b =>
                {
                    b.HasOne("MusicWpf.Models.Album", "Album")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("AlbumGenres_AlbumId_fkey");

                    b.HasOne("MusicWpf.Models.Genre", "Genre")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("AlbumGenres_GenreId_fkey");

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusicWpf.Models.AlbumTrack", b =>
                {
                    b.HasOne("MusicWpf.Models.Album", "Album")
                        .WithMany("AlbumTracks")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("AlbumTracks_AlbumId_fkey");

                    b.HasOne("MusicWpf.Models.Track", "Tracks")
                        .WithMany("AlbumTracks")
                        .HasForeignKey("TracksId")
                        .IsRequired()
                        .HasConstraintName("AlbumTracks_TracksId_fkey");

                    b.Navigation("Album");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicWpf.Models.ArtistTrack", b =>
                {
                    b.HasOne("MusicWpf.Models.Artist", "Artist")
                        .WithMany("ArtistTracks")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("ArtistTracks_ArtistId_fkey");

                    b.HasOne("MusicWpf.Models.Track", "Track")
                        .WithMany("ArtistTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("ArtistTracks_TrackId_fkey");

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicWpf.Models.GenreArtist", b =>
                {
                    b.HasOne("MusicWpf.Models.Artist", "Artist")
                        .WithMany("GenreArtists")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("GenreArtist_ArtistId_fkey");

                    b.HasOne("MusicWpf.Models.Genre", "Genre")
                        .WithMany("GenreArtists")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("GenreArtist_GenreId_fkey");

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusicWpf.Models.Playlist", b =>
                {
                    b.HasOne("MusicWpf.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Playlist_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicWpf.Models.PlaylistTag", b =>
                {
                    b.HasOne("MusicWpf.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("PlaylistTags_PlaylistId_fkey");

                    b.HasOne("MusicWpf.Models.Tag", "Tags")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("TagsId")
                        .IsRequired()
                        .HasConstraintName("PlaylistTags_TagsId_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MusicWpf.Models.PlaylistsUser", b =>
                {
                    b.HasOne("MusicWpf.Models.Playlist", "Playlists")
                        .WithMany("PlaylistsUsers")
                        .HasForeignKey("PlaylistsId")
                        .IsRequired()
                        .HasConstraintName("PlaylistsUser_PlaylistsId_fkey");

                    b.HasOne("MusicWpf.Models.User", "User")
                        .WithMany("PlaylistsUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("PlaylistsUser_UserId_fkey");

                    b.Navigation("Playlists");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicWpf.Models.TracksGenre", b =>
                {
                    b.HasOne("MusicWpf.Models.Genre", "Genres")
                        .WithMany("TracksGenres")
                        .HasForeignKey("GenresId")
                        .IsRequired()
                        .HasConstraintName("TracksGenres_GenresId_fkey");

                    b.HasOne("MusicWpf.Models.Track", "Tracks")
                        .WithMany("TracksGenres")
                        .HasForeignKey("TracksId")
                        .IsRequired()
                        .HasConstraintName("TracksGenres_TracksId_fkey");

                    b.Navigation("Genres");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicWpf.Models.TracksPlaylist", b =>
                {
                    b.HasOne("MusicWpf.Models.Playlist", "Playlist")
                        .WithMany("TracksPlaylists")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("TracksPlaylist_PlaylistId_fkey");

                    b.HasOne("MusicWpf.Models.Track", "Tracks")
                        .WithMany("TracksPlaylists")
                        .HasForeignKey("TracksId")
                        .HasConstraintName("TracksPlaylist_TracksId_fkey");

                    b.Navigation("Playlist");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicWpf.Models.User", b =>
                {
                    b.HasOne("MusicWpf.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("User_RoleId_fkey");

                    b.HasOne("MusicWpf.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("User_SubscriptionId_fkey");

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MusicWpf.Models.Album", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("AlbumTracks");
                });

            modelBuilder.Entity("MusicWpf.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ArtistTracks");

                    b.Navigation("GenreArtists");
                });

            modelBuilder.Entity("MusicWpf.Models.Genre", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("GenreArtists");

                    b.Navigation("TracksGenres");
                });

            modelBuilder.Entity("MusicWpf.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistTags");

                    b.Navigation("PlaylistsUsers");

                    b.Navigation("TracksPlaylists");
                });

            modelBuilder.Entity("MusicWpf.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MusicWpf.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MusicWpf.Models.Tag", b =>
                {
                    b.Navigation("PlaylistTags");
                });

            modelBuilder.Entity("MusicWpf.Models.Track", b =>
                {
                    b.Navigation("AlbumTracks");

                    b.Navigation("ArtistTracks");

                    b.Navigation("TracksGenres");

                    b.Navigation("TracksPlaylists");
                });

            modelBuilder.Entity("MusicWpf.Models.User", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("PlaylistsUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
