// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musick.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Musick.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20251127090702_DodatkoBD")]
    partial class DodatkoBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumsGenre", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    b.Property<int>("GenresId")
                        .HasColumnType("integer")
                        .HasColumnName("GenresID");

                    b.HasKey("AlbumId", "GenresId")
                        .HasName("albumsgenres_pk");

                    b.HasIndex("GenresId");

                    b.ToTable("AlbumsGenres", (string)null);
                });

            modelBuilder.Entity("ArtistsGenre", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ArtistID");

                    b.Property<int>("GenresId")
                        .HasColumnType("integer")
                        .HasColumnName("GenresID");

                    b.HasKey("ArtistId", "GenresId")
                        .HasName("artistsgenres_pk");

                    b.HasIndex("GenresId");

                    b.ToTable("ArtistsGenres", (string)null);
                });

            modelBuilder.Entity("Musick.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumCoverPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("ArtistID");

                    b.Property<int>("RealiseDate")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("TotalDuration")
                        .HasColumnType("time without time zone");

                    b.HasKey("AlbumId")
                        .HasName("Albums_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Musick.Models.Artist", b =>
                {
                    b.Property<int>("ArtistsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ArtistsID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistsId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("CountryID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("YearsActive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistsId")
                        .HasName("Artists_pkey");

                    b.HasIndex("CountryId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Musick.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CountryID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CounryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId")
                        .HasName("Countries_pkey");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Musick.Models.Genre", b =>
                {
                    b.Property<int>("GenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("GenresID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenresId"));

                    b.Property<string>("GenresName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenresId")
                        .HasName("Genres_pkey");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Musick.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PlaylistID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistId"));

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("PlaylistId")
                        .HasName("Playlists_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Musick.Models.Rol", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId")
                        .HasName("Rols_pkey");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("Musick.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SubscriptionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("SubscriptionName")
                        .HasColumnType("text");

                    b.HasKey("SubscriptionId")
                        .HasName("Subscriptions_pkey");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Musick.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("NameTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId")
                        .HasName("Tags_pkey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Musick.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrackID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    b.Property<int>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("RealiseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrackId")
                        .HasName("Tracks_pkey");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Musick.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBan")
                        .HasColumnType("boolean")
                        .HasColumnName("IsBan?");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("PlaylistID");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("SubscriptionID");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("Users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlaylstTag", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PlaylistID");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "TagId")
                        .HasName("playlsttags_pk");

                    b.HasIndex("TagId");

                    b.ToTable("PlaylstTags", (string)null);
                });

            modelBuilder.Entity("TracksArtist", b =>
                {
                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("TrackID");

                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ArtistID");

                    b.HasKey("TrackId", "ArtistId")
                        .HasName("tracksartists_pk");

                    b.HasIndex("ArtistId");

                    b.ToTable("TracksArtists", (string)null);
                });

            modelBuilder.Entity("TracksGenre", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrackID");

                    b.Property<int>("GenresId")
                        .HasColumnType("integer")
                        .HasColumnName("GenresID");

                    b.HasKey("TrackId", "GenresId")
                        .HasName("tracksgenres_pk");

                    b.HasIndex("GenresId");

                    b.ToTable("TracksGenres", (string)null);
                });

            modelBuilder.Entity("TracksPlaylist", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrackID");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("PlaylistID");

                    b.HasKey("TrackId", "PlaylistId")
                        .HasName("tracksplaylists_pk");

                    b.HasIndex("PlaylistId");

                    b.ToTable("TracksPlaylists", (string)null);
                });

            modelBuilder.Entity("UsersPlaylist", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("PlaylistID");

                    b.HasKey("UserId", "PlaylistId")
                        .HasName("usersplaylists_pk");

                    b.HasIndex("PlaylistId");

                    b.ToTable("UsersPlaylists", (string)null);
                });

            modelBuilder.Entity("AlbumsGenre", b =>
                {
                    b.HasOne("Musick.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("AlbumsGenres_AlbumID_fkey");

                    b.HasOne("Musick.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .IsRequired()
                        .HasConstraintName("AlbumsGenres_GenresID_fkey");
                });

            modelBuilder.Entity("ArtistsGenre", b =>
                {
                    b.HasOne("Musick.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("ArtistsGenres_ArtistID_fkey");

                    b.HasOne("Musick.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .IsRequired()
                        .HasConstraintName("ArtistsGenres_GenresID_fkey");
                });

            modelBuilder.Entity("Musick.Models.Album", b =>
                {
                    b.HasOne("Musick.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("Albums_ArtistID_fkey");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Musick.Models.Artist", b =>
                {
                    b.HasOne("Musick.Models.Country", "Country")
                        .WithMany("Artists")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("Artists_CountryID_fkey");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Musick.Models.Playlist", b =>
                {
                    b.HasOne("Musick.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("playlists_users_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musick.Models.Track", b =>
                {
                    b.HasOne("Musick.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("tracks_albums_fk");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Musick.Models.User", b =>
                {
                    b.HasOne("Musick.Models.Rol", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("Users_RoleID_fkey");

                    b.HasOne("Musick.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("Users_SubscriptionID_fkey");

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PlaylstTag", b =>
                {
                    b.HasOne("Musick.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("PlaylstTags_PlaylistID_fkey");

                    b.HasOne("Musick.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("PlaylstTags_TagId_fkey");
                });

            modelBuilder.Entity("TracksArtist", b =>
                {
                    b.HasOne("Musick.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("TracksArtists_ArtistID_fkey");

                    b.HasOne("Musick.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("TracksArtists_TrackID_fkey");
                });

            modelBuilder.Entity("TracksGenre", b =>
                {
                    b.HasOne("Musick.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .IsRequired()
                        .HasConstraintName("TracksGenres_GenresID_fkey");

                    b.HasOne("Musick.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("TracksGenres_TrackID_fkey");
                });

            modelBuilder.Entity("TracksPlaylist", b =>
                {
                    b.HasOne("Musick.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("TracksPlaylists_PlaylistID_fkey");

                    b.HasOne("Musick.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("TracksPlaylists_TrackID_fkey");
                });

            modelBuilder.Entity("UsersPlaylist", b =>
                {
                    b.HasOne("Musick.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("usersplaylists_playlists_fk");

                    b.HasOne("Musick.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("usersplaylists_users_fk");
                });

            modelBuilder.Entity("Musick.Models.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Musick.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Musick.Models.Country", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Musick.Models.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Musick.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Musick.Models.User", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
