// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PraktikaMusicF.Context;

#nullable disable

namespace PraktikaMusicF.Migrations
{
    [DbContext(typeof(MusicBdFContext))]
    partial class MusicBdFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PraktikaMusicF.Models.Album", b =>
                {
                    b.Property<int>("AlbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alb_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbId"));

                    b.Property<string>("AlbImage")
                        .HasColumnType("text")
                        .HasColumnName("alb_image");

                    b.Property<string>("AlbName")
                        .HasColumnType("character varying")
                        .HasColumnName("alb_name");

                    b.Property<DateOnly?>("AlbRelease")
                        .HasColumnType("date")
                        .HasColumnName("alb_release");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.HasKey("AlbId")
                        .HasName("Albums_pkey");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.AlbumsGenre", b =>
                {
                    b.Property<int>("AlbGenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alb_genres_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbGenresId"));

                    b.Property<int?>("AlbId")
                        .HasColumnType("integer")
                        .HasColumnName("alb_id");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("AlbGenresId")
                        .HasName("AlbumsGenres_pkey");

                    b.HasIndex("AlbId");

                    b.HasIndex("GenreId");

                    b.ToTable("AlbumsGenres");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Artist", b =>
                {
                    b.Property<int>("ArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtId"));

                    b.Property<string>("ArtDesc")
                        .HasColumnType("text")
                        .HasColumnName("art_desc");

                    b.Property<string>("ArtName")
                        .HasColumnType("character varying")
                        .HasColumnName("art_name");

                    b.Property<string>("ArtPhotoPath")
                        .HasColumnType("text")
                        .HasColumnName("art_photo_path");

                    b.Property<string>("YearActive")
                        .HasColumnType("text")
                        .HasColumnName("year_active");

                    b.HasKey("ArtId")
                        .HasName("Artist_pkey");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("PraktikaMusicF.Models.ArtistGenre", b =>
                {
                    b.Property<int>("ArtGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("art_genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtGenreId"));

                    b.Property<int?>("ArtId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("ArtGenreId")
                        .HasName("ArtistGenres_pkey");

                    b.HasIndex("ArtId");

                    b.HasIndex("GenreId");

                    b.ToTable("ArtistGenres");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenresName")
                        .HasColumnType("character varying")
                        .HasColumnName("genres_name");

                    b.HasKey("GenreId")
                        .HasName("Genres_pkey");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Playlist", b =>
                {
                    b.Property<int>("PlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlId"));

                    b.Property<DateOnly?>("PlDateCreate")
                        .HasColumnType("date")
                        .HasColumnName("pl_date_create");

                    b.Property<string>("PlDesc")
                        .HasColumnType("text")
                        .HasColumnName("pl_desc");

                    b.Property<int?>("PlLikes")
                        .HasColumnType("integer")
                        .HasColumnName("pl_likes");

                    b.Property<string>("PlName")
                        .HasColumnType("character varying")
                        .HasColumnName("pl_name");

                    b.Property<int?>("PlTracksQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("pl_tracks_quantity");

                    b.Property<TimeOnly?>("TotalDuration")
                        .HasColumnType("time without time zone")
                        .HasColumnName("total_duration");

                    b.HasKey("PlId")
                        .HasName("Playlist_pkey");

                    b.ToTable("Playlist", (string)null);
                });

            modelBuilder.Entity("PraktikaMusicF.Models.PlaylistCreator", b =>
                {
                    b.Property<int>("CrPlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cr_pl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CrPlId"));

                    b.Property<int?>("PlId")
                        .HasColumnType("integer")
                        .HasColumnName("pl_id");

                    b.Property<int?>("UsrId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.HasKey("CrPlId")
                        .HasName("PlaylistCreator_pkey");

                    b.HasIndex("PlId");

                    b.HasIndex("UsrId");

                    b.ToTable("PlaylistCreator", (string)null);
                });

            modelBuilder.Entity("PraktikaMusicF.Models.PlaylistTrack", b =>
                {
                    b.Property<int>("PlTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pl_track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlTrackId"));

                    b.Property<int?>("PlId")
                        .HasColumnType("integer")
                        .HasColumnName("pl_id");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("PlTrackId")
                        .HasName("PlaylistTracks_pkey");

                    b.HasIndex("PlId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.PlaylistsTag", b =>
                {
                    b.Property<int>("PlTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pl_tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlTagId"));

                    b.Property<int?>("PlId")
                        .HasColumnType("integer")
                        .HasColumnName("pl_id");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("PlTagId")
                        .HasName("PlaylistsTags_pkey");

                    b.HasIndex("PlId");

                    b.HasIndex("TagId");

                    b.ToTable("PlaylistsTags");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("Roles_pkey");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Subscription", b =>
                {
                    b.Property<int>("SubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sub_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubId"));

                    b.Property<string>("SubName")
                        .HasColumnType("character varying")
                        .HasColumnName("sub_name");

                    b.HasKey("SubId")
                        .HasName("Subscription_pkey");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .HasColumnType("text")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("Tags_pkey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackId"));

                    b.Property<int?>("AlbId")
                        .HasColumnType("integer")
                        .HasColumnName("alb_id");

                    b.Property<int?>("TrackBitrate")
                        .HasColumnType("integer")
                        .HasColumnName("track_bitrate");

                    b.Property<long?>("TrackCount")
                        .HasColumnType("bigint")
                        .HasColumnName("track_count");

                    b.Property<long?>("TrackDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("track_duration");

                    b.Property<string>("TrackName")
                        .HasColumnType("character varying")
                        .HasColumnName("track_name");

                    b.Property<string>("TrackPath")
                        .HasColumnType("text")
                        .HasColumnName("track_path");

                    b.Property<double?>("TrackRating")
                        .HasColumnType("double precision")
                        .HasColumnName("track_rating");

                    b.Property<DateOnly?>("TrackRelease")
                        .HasColumnType("date")
                        .HasColumnName("track_release");

                    b.HasKey("TrackId")
                        .HasName("Track_pkey");

                    b.HasIndex("AlbId");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("PraktikaMusicF.Models.TrackArtist", b =>
                {
                    b.Property<int>("TrackArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("track_art_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackArtId"));

                    b.Property<int?>("ArtId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("TrackArtId")
                        .HasName("TrackArtists_pkey");

                    b.HasIndex("ArtId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.TrackList", b =>
                {
                    b.Property<int>("TrackListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("track_list_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackListId"));

                    b.Property<int?>("AlbId")
                        .HasColumnType("integer")
                        .HasColumnName("alb_id");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("TrackListId")
                        .HasName("TrackList_pkey");

                    b.HasIndex("AlbId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackList", (string)null);
                });

            modelBuilder.Entity("PraktikaMusicF.Models.TracksGenre", b =>
                {
                    b.Property<int>("TrackGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("track_genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackGenreId"));

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("TrackGenreId")
                        .HasName("TracksGenres_pkey");

                    b.HasIndex("GenreId");

                    b.HasIndex("TrackId");

                    b.ToTable("TracksGenres");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.User", b =>
                {
                    b.Property<int>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsrId"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int?>("SubId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_id");

                    b.Property<string>("UsrEmail")
                        .HasColumnType("text")
                        .HasColumnName("usr_email");

                    b.Property<string>("UsrFName")
                        .HasColumnType("text")
                        .HasColumnName("usr_f_name");

                    b.Property<DateOnly?>("UsrLastEntry")
                        .HasColumnType("date")
                        .HasColumnName("usr_last_entry");

                    b.Property<string>("UsrPass")
                        .HasColumnType("text")
                        .HasColumnName("usr_pass");

                    b.Property<int?>("UsrPlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_playlist_id");

                    b.Property<DateOnly?>("UsrRegDate")
                        .HasColumnType("date")
                        .HasColumnName("usr_reg_date");

                    b.HasKey("UsrId")
                        .HasName("Users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubId");

                    b.HasIndex("UsrPlaylistId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Album", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("albums_artist_fk");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.AlbumsGenre", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Album", "Alb")
                        .WithMany("AlbumsGenres")
                        .HasForeignKey("AlbId")
                        .HasConstraintName("albumsgenres_albums_fk");

                    b.HasOne("PraktikaMusicF.Models.Genre", "Genre")
                        .WithMany("AlbumsGenres")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("albumsgenres_genres_fk");

                    b.Navigation("Alb");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.ArtistGenre", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Artist", "Art")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtId")
                        .HasConstraintName("artistgenres_artist_fk");

                    b.HasOne("PraktikaMusicF.Models.Genre", "Genre")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("artistgenres_genres_fk");

                    b.Navigation("Art");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.PlaylistCreator", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Playlist", "Pl")
                        .WithMany("PlaylistCreators")
                        .HasForeignKey("PlId")
                        .HasConstraintName("playlistcreator_playlist_fk");

                    b.HasOne("PraktikaMusicF.Models.User", "Usr")
                        .WithMany("PlaylistCreators")
                        .HasForeignKey("UsrId")
                        .HasConstraintName("playlistcreator_users_fk");

                    b.Navigation("Pl");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.PlaylistTrack", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Playlist", "Pl")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlId")
                        .HasConstraintName("playlisttracks_playlist_fk");

                    b.HasOne("PraktikaMusicF.Models.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("playlisttracks_track_fk");

                    b.Navigation("Pl");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.PlaylistsTag", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Playlist", "Pl")
                        .WithMany("PlaylistsTags")
                        .HasForeignKey("PlId")
                        .HasConstraintName("playliststags_playlist_fk");

                    b.HasOne("PraktikaMusicF.Models.Tag", "Tag")
                        .WithMany("PlaylistsTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("playliststags_tags_fk");

                    b.Navigation("Pl");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Track", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Album", "Alb")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbId")
                        .HasConstraintName("track_albums_fk");

                    b.Navigation("Alb");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.TrackArtist", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Artist", "Art")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtId")
                        .HasConstraintName("trackartists_artist_fk");

                    b.HasOne("PraktikaMusicF.Models.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("trackartists_track_fk");

                    b.Navigation("Art");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.TrackList", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Album", "Alb")
                        .WithMany("TrackLists")
                        .HasForeignKey("AlbId")
                        .HasConstraintName("tracklist_albums_fk");

                    b.HasOne("PraktikaMusicF.Models.Track", "Track")
                        .WithMany("TrackLists")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("tracklist_track_fk");

                    b.Navigation("Alb");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.TracksGenre", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Genre", "Genre")
                        .WithMany("TracksGenres")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("tracksgenres_genres_fk");

                    b.HasOne("PraktikaMusicF.Models.Track", "Track")
                        .WithMany("TracksGenres")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("tracksgenres_track_fk");

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.User", b =>
                {
                    b.HasOne("PraktikaMusicF.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("users_roles_fk");

                    b.HasOne("PraktikaMusicF.Models.Subscription", "Sub")
                        .WithMany("Users")
                        .HasForeignKey("SubId")
                        .HasConstraintName("users_subscription_fk");

                    b.HasOne("PraktikaMusicF.Models.Playlist", "UsrPlaylist")
                        .WithMany("Users")
                        .HasForeignKey("UsrPlaylistId")
                        .HasConstraintName("users_playlist_fk");

                    b.Navigation("Role");

                    b.Navigation("Sub");

                    b.Navigation("UsrPlaylist");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Album", b =>
                {
                    b.Navigation("AlbumsGenres");

                    b.Navigation("TrackLists");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ArtistGenres");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Genre", b =>
                {
                    b.Navigation("AlbumsGenres");

                    b.Navigation("ArtistGenres");

                    b.Navigation("TracksGenres");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistCreators");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("PlaylistsTags");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Tag", b =>
                {
                    b.Navigation("PlaylistsTags");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.Track", b =>
                {
                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackArtists");

                    b.Navigation("TrackLists");

                    b.Navigation("TracksGenres");
                });

            modelBuilder.Entity("PraktikaMusicF.Models.User", b =>
                {
                    b.Navigation("PlaylistCreators");
                });
#pragma warning restore 612, 618
        }
    }
}
