--
-- PostgreSQL database dump
--

\restrict mUNBQdImesV0xucOUHCudfq0ZC5ab7NbSy63B0WSJLzfcHngyV5aX9uTSx4I0fF

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7

-- Started on 2025-11-27 16:01:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3522 (class 1262 OID 17040)
-- Name: spotify; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE spotify WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE spotify OWNER TO postgres;

\unrestrict mUNBQdImesV0xucOUHCudfq0ZC5ab7NbSy63B0WSJLzfcHngyV5aX9uTSx4I0fF
\connect spotify
\restrict mUNBQdImesV0xucOUHCudfq0ZC5ab7NbSy63B0WSJLzfcHngyV5aX9uTSx4I0fF

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3523 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 228 (class 1259 OID 17092)
-- Name: Albums; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Albums" (
    "Id" integer NOT NULL,
    "AlbumTitle" text NOT NULL,
    "ArtistId" integer NOT NULL,
    "ReleaseYear" integer NOT NULL,
    "CoverPath" text NOT NULL,
    "TotalDuration" time without time zone NOT NULL
);


ALTER TABLE public."Albums" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17091)
-- Name: Albums_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Albums" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Albums_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17042)
-- Name: Artists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Artists" (
    "Id" integer NOT NULL,
    "ArtistName" text NOT NULL,
    "CountryId" integer NOT NULL,
    "Description" text NOT NULL,
    "PhotoPath" text NOT NULL,
    "StartYearActive" integer NOT NULL,
    "EndYearActive" integer NOT NULL
);


ALTER TABLE public."Artists" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17041)
-- Name: ArtistName_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Artists" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ArtistName_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17303)
-- Name: ArtistsTracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ArtistsTracks" (
    "ArtistId" integer NOT NULL,
    "TrackId" integer NOT NULL
);


ALTER TABLE public."ArtistsTracks" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17261)
-- Name: Countryes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Countryes" (
    "Id" integer NOT NULL,
    "Country" text NOT NULL
);


ALTER TABLE public."Countryes" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17260)
-- Name: Countryes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Countryes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Countryes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17050)
-- Name: Genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Genres" (
    "Id" integer NOT NULL,
    "Genre" text NOT NULL
);


ALTER TABLE public."Genres" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17224)
-- Name: GenresAlbums; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GenresAlbums" (
    "GenreId" integer NOT NULL,
    "AlbumId" integer NOT NULL
);


ALTER TABLE public."GenresAlbums" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17188)
-- Name: GenresArtists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GenresArtists" (
    "GenreId" integer NOT NULL,
    "ArtistId" integer NOT NULL
);


ALTER TABLE public."GenresArtists" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17239)
-- Name: GenresTracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GenresTracks" (
    "GenreId" integer NOT NULL,
    "TrackId" integer NOT NULL
);


ALTER TABLE public."GenresTracks" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17049)
-- Name: Genres_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Genres" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Genres_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17108)
-- Name: Playlists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Playlists" (
    "Id" integer NOT NULL,
    "PlaylistName" text NOT NULL,
    "UserId" integer,
    "DateCreated" date NOT NULL,
    "Likes" integer NOT NULL,
    "Description" text
);


ALTER TABLE public."Playlists" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17107)
-- Name: Playlist_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Playlists" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Playlist_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17128)
-- Name: PlaylistsTags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlaylistsTags" (
    "PlaylistId" integer NOT NULL,
    "TagId" integer NOT NULL
);


ALTER TABLE public."PlaylistsTags" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17143)
-- Name: PlaylistsTracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlaylistsTracks" (
    "PlaylistId" integer NOT NULL,
    "TrackId" integer NOT NULL
);


ALTER TABLE public."PlaylistsTracks" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17158)
-- Name: PlaylistsUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlaylistsUsers" (
    "PlaylistId" integer NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE public."PlaylistsUsers" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17058)
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17057)
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17066)
-- Name: Subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Subscriptions" (
    "Id" integer NOT NULL,
    "Subscription" text NOT NULL
);


ALTER TABLE public."Subscriptions" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17065)
-- Name: Subscriptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Subscriptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Subscriptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17121)
-- Name: Tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tags" (
    "Id" integer NOT NULL,
    "Tag" text NOT NULL
);


ALTER TABLE public."Tags" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17120)
-- Name: Tags_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tags_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17100)
-- Name: Tracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tracks" (
    "Id" integer NOT NULL,
    "TrackName" text NOT NULL,
    "Duration" interval NOT NULL,
    "ReleaseDate" date NOT NULL,
    "Bitrate" integer NOT NULL,
    "FilePath" text NOT NULL,
    "Rating" numeric NOT NULL,
    "PlayCount" integer NOT NULL,
    "AlbumId" integer NOT NULL
);


ALTER TABLE public."Tracks" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17099)
-- Name: Tracks_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tracks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tracks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17074)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "RoleId" integer NOT NULL,
    "SubscriptionId" integer NOT NULL,
    "RegistrationDate" date NOT NULL,
    "LastLogin" date NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17601)
-- Name: UsersHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UsersHistories" (
    "UserHistoryId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "History" timestamp without time zone NOT NULL
);


ALTER TABLE public."UsersHistories" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17073)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3500 (class 0 OID 17092)
-- Dependencies: 228
-- Data for Name: Albums; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Albums" VALUES (1, 'あなたを待って', 27, 2015, 'https://i.scdn.co/image/ab67616d0000b273fcc3cb5cc1166a95b86f5e6e', '00:00:00');
INSERT INTO public."Albums" VALUES (2, 'Circle', 19, 2022, 'https://i.scdn.co/image/ab67616d0000b273f0f4f4f180ea0f32ac2c5f8f', '00:00:00');
INSERT INTO public."Albums" VALUES (3, 'CHOMPO III', 8, 2025, 'https://i.scdn.co/image/ab67616d0000b273aadd94c74f32483d503fb0ab', '00:00:00');
INSERT INTO public."Albums" VALUES (4, 'Metalicious', 22, 2025, 'https://i.scdn.co/image/ab67616d0000b27368e7513b4ca1da14da0a81e6', '00:00:00');
INSERT INTO public."Albums" VALUES (5, 'The Masquerade (Zardonic & Toronto Is Broken Remix)', 3, 2025, 'https://i.scdn.co/image/ab67616d0000b273b9bb9b27f5aeb0e1a1475707', '00:00:00');
INSERT INTO public."Albums" VALUES (6, 'The Machine', 22, 2025, 'https://i.scdn.co/image/ab67616d0000b27328700d650196f5918a0578bf', '00:00:00');
INSERT INTO public."Albums" VALUES (7, 'Run', 21, 2025, 'https://i.scdn.co/image/ab67616d0000b273af743f04ff7cc6ae7300929f', '00:00:00');
INSERT INTO public."Albums" VALUES (8, 'Barbara Barbara, we face a shining future', 11, 2016, 'https://i.scdn.co/image/ab67616d0000b273cf5cdbf0397a8a71c9fd0395', '00:00:00');
INSERT INTO public."Albums" VALUES (9, 'Data Destruction', 26, 2025, 'https://i.scdn.co/image/ab67616d0000b273c6ad3e09b75355deee5b732d', '00:00:00');
INSERT INTO public."Albums" VALUES (10, 'Grave', 39, 2025, 'https://i.scdn.co/image/ab67616d0000b273659f2e9dc34715a487f073be', '00:00:00');
INSERT INTO public."Albums" VALUES (11, 'The Fragile', 12, 1999, 'https://i.scdn.co/image/ab67616d0000b273237a21c8ba1bfc2d85a83585', '00:00:00');
INSERT INTO public."Albums" VALUES (12, 'Further Down The Spiral', 12, 1995, 'https://i.scdn.co/image/ab67616d0000b273551ecb57cda40ae833e3e5b1', '00:00:00');
INSERT INTO public."Albums" VALUES (13, 'Liquid (Bonus Track Version)', 2, 2000, 'https://i.scdn.co/image/ab67616d0000b273211808193df8743aedb1038b', '00:00:00');
INSERT INTO public."Albums" VALUES (14, 'The Day Is My Enemy (Expanded Edition)', 5, 2015, 'https://i.scdn.co/image/ab67616d0000b273872772e0b165e57a104fd37a', '00:00:00');
INSERT INTO public."Albums" VALUES (15, 'Final Destination', 14, 2025, 'https://i.scdn.co/image/ab67616d0000b273857bb2eff1c145e26e9a2c1c', '00:00:00');
INSERT INTO public."Albums" VALUES (16, 'Fuze', 40, 2025, 'https://i.scdn.co/image/ab67616d0000b27362d6852a9461f7c5579097c6', '00:00:00');
INSERT INTO public."Albums" VALUES (17, 'NO MERCY III', 38, 2025, 'https://i.scdn.co/image/ab67616d0000b273a10a1e401fc110168dfd02f3', '00:00:00');
INSERT INTO public."Albums" VALUES (18, 'As Alive As You Need Me To Be', 12, 2025, 'https://i.scdn.co/image/ab67616d0000b27317ff2581a6b924fb3a704395', '00:00:00');
INSERT INTO public."Albums" VALUES (19, 'общедомовой', 16, 2025, 'https://i.scdn.co/image/ab67616d0000b273f11a5383c11039c003e9008b', '00:00:00');
INSERT INTO public."Albums" VALUES (20, 'Ghosts V: Together', 12, 2020, 'https://i.scdn.co/image/ab67616d0000b27327c5a582320e08258ec13d0a', '00:00:00');
INSERT INTO public."Albums" VALUES (21, 'The Star', 25, 2025, 'https://i.scdn.co/image/ab67616d0000b2731e01b0b41fa3bf96bab342cb', '00:00:00');
INSERT INTO public."Albums" VALUES (22, 'Subhuman', 2, 2007, 'https://i.scdn.co/image/ab67616d0000b273ce0298116be15cb81f91a1aa', '00:00:00');
INSERT INTO public."Albums" VALUES (23, 'Overload 2K', 39, 2025, 'https://i.scdn.co/image/ab67616d0000b273a24c69273fb3656b3ecb92a7', '00:00:00');
INSERT INTO public."Albums" VALUES (24, 'Never, Never, Land', 34, 2003, 'https://i.scdn.co/image/ab67616d0000b273894c4f974159696026573eb5', '00:00:00');
INSERT INTO public."Albums" VALUES (25, 'Cinematic Soundscape', 28, 2012, 'https://i.scdn.co/image/ab67616d0000b27381c4fc91dc2abd939c2c705f', '00:00:00');
INSERT INTO public."Albums" VALUES (26, 'ORDINARY LOSS', 17, 2025, 'https://i.scdn.co/image/ab67616d0000b27367bd88cd7a659c93b34b0688', '00:00:00');
INSERT INTO public."Albums" VALUES (27, 'Ghost City Daze', 6, 2022, 'https://i.scdn.co/image/ab67616d0000b273ab65f724c2fdf067999d8d16', '00:00:00');
INSERT INTO public."Albums" VALUES (28, 'Baby', 36, 2025, 'https://i.scdn.co/image/ab67616d0000b273fc679c0d97b173113141a42b', '00:00:00');
INSERT INTO public."Albums" VALUES (29, 'Atomic Heart, Vol.5 (Original Game Soundtrack)', 35, 2025, 'https://i.scdn.co/image/ab67616d0000b2731a24aab10d2b27d63175c37a', '00:00:00');
INSERT INTO public."Albums" VALUES (30, 'Wall I Was', 4, 2025, 'https://i.scdn.co/image/ab67616d0000b273710d4624a5a1b87b70b56bb2', '00:00:00');
INSERT INTO public."Albums" VALUES (31, 'Oblivion With Bells', 11, 2007, 'https://i.scdn.co/image/ab67616d0000b2736b09703b5a9e23a2c669012b', '00:00:00');
INSERT INTO public."Albums" VALUES (32, 'Breed (feat. REEBZ)', 19, 2023, 'https://i.scdn.co/image/ab67616d0000b2737163994ea19cc74c0bbfb31e', '00:00:00');
INSERT INTO public."Albums" VALUES (33, 'Repentance', 25, 2025, 'https://i.scdn.co/image/ab67616d0000b2730f423970a440915f6750e11e', '00:00:00');
INSERT INTO public."Albums" VALUES (34, 'Muleta', 25, 2025, 'https://i.scdn.co/image/ab67616d0000b273adebc14e80184ee7cc2e36b8', '00:00:00');
INSERT INTO public."Albums" VALUES (35, 'GOFASTER (YANA100)', 19, 2025, 'https://i.scdn.co/image/ab67616d0000b2735ff50f46b8b8720981957d51', '00:00:00');
INSERT INTO public."Albums" VALUES (36, 'SOMEWHEREIBELONG', 19, 2025, 'https://i.scdn.co/image/ab67616d0000b27328dc64c5aa8c59dd37a7d820', '00:00:00');
INSERT INTO public."Albums" VALUES (37, 'Lvstlove', 42, 2025, 'https://i.scdn.co/image/ab67616d0000b2737348b951edbf4bb86854e806', '00:00:00');
INSERT INTO public."Albums" VALUES (38, 'Bloodline (Bonus Tracks)', 2, 1992, 'https://i.scdn.co/image/ab67616d0000b273c74e21dfa7e9470c0c980f9f', '00:00:00');
INSERT INTO public."Albums" VALUES (39, 'Formula Of Fear', 28, 2008, 'https://i.scdn.co/image/ab67616d0000b27359566bca173ee54657bd5f8d', '00:00:00');
INSERT INTO public."Albums" VALUES (40, 'Moments In Everglow', 24, 2025, 'https://i.scdn.co/image/ab67616d0000b27379edc5965038d4923dff96b0', '00:00:00');
INSERT INTO public."Albums" VALUES (41, 'Siren Of The Storm', 28, 2025, 'https://i.scdn.co/image/ab67616d0000b273628b577615d97f6837e30b73', '00:00:00');
INSERT INTO public."Albums" VALUES (42, 'I See Red', 10, 2025, 'https://i.scdn.co/image/ab67616d0000b2737f34486112bf81e38838a429', '00:00:00');
INSERT INTO public."Albums" VALUES (43, 'Call of Duty®: Black Ops 6 - Zombies "The Tomb" (Original Soundtrack)', 15, 2025, 'https://i.scdn.co/image/ab67616d0000b2732db3154893852b63232e1466', '00:00:00');


--
-- TOC entry 3490 (class 0 OID 17042)
-- Dependencies: 218
-- Data for Name: Artists; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Artists" VALUES (1, 'Sebotage', 1, 'Исполнитель Sebotage известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebe8500fa9b789bfc15faf1c26', 2000, 2025);
INSERT INTO public."Artists" VALUES (2, 'Recoil', 1, 'Исполнитель Recoil известен своими треками на Spotify.', 'https://i.scdn.co/image/8a55f8b98045192cf6f96cdaf0a10a87a1333209', 2000, 2025);
INSERT INTO public."Artists" VALUES (3, 'CANTERVICE', 1, 'Исполнитель CANTERVICE известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebdc3edcf7e8414d791d224ab4', 2000, 2025);
INSERT INTO public."Artists" VALUES (4, 'Naked Flames', 1, 'Исполнитель Naked Flames известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb864a03d162414c8ff3eb7b21', 2000, 2025);
INSERT INTO public."Artists" VALUES (5, 'The Prodigy', 1, 'Исполнитель The Prodigy известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb147841812056c247407811f3', 2000, 2025);
INSERT INTO public."Artists" VALUES (6, 'Hong Kong Express', 1, 'Исполнитель Hong Kong Express известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb26fbeeac4e8c45780b3b3a7d', 2000, 2025);
INSERT INTO public."Artists" VALUES (7, 'Boom Kitty', 1, 'Исполнитель Boom Kitty известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb0537e4e52505684d70275b45', 2000, 2025);
INSERT INTO public."Artists" VALUES (8, 'CHOMPO', 1, 'Исполнитель CHOMPO известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebab8bdcdcebb63c80fb868a75', 2000, 2025);
INSERT INTO public."Artists" VALUES (9, 'Trivium', 1, 'Исполнитель Trivium известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebab21a41e346730ff64be53c2', 2000, 2025);
INSERT INTO public."Artists" VALUES (10, 'Ladytron', 1, 'Исполнитель Ladytron известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebb948a9242e7ff017fb0d1173', 2000, 2025);
INSERT INTO public."Artists" VALUES (11, 'Underworld', 1, 'Исполнитель Underworld известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb5cfa742c32b2f8c23f94cf7e', 2000, 2025);
INSERT INTO public."Artists" VALUES (12, 'Nine Inch Nails', 1, 'Исполнитель Nine Inch Nails известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb752fca27c5b839ea47d5100d', 2000, 2025);
INSERT INTO public."Artists" VALUES (13, 'Solter', 1, 'Исполнитель Solter известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb20b33946a5d8579f780d6d7c', 2000, 2025);
INSERT INTO public."Artists" VALUES (14, 'Kurai mizu', 1, 'Исполнитель Kurai mizu известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb52980e5c7d56a2b51fd5914d', 2000, 2025);
INSERT INTO public."Artists" VALUES (15, 'Kevin Sherwood', 1, 'Исполнитель Kevin Sherwood известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb82a01d3b0a1890a78e9e527a', 2000, 2025);
INSERT INTO public."Artists" VALUES (16, 'AL-90', 1, 'Исполнитель AL-90 известен своими треками на Spotify.', 'https://i.scdn.co/image/ab67616d0000b2738fe600c89360e4a56ac26c7d', 2000, 2025);
INSERT INTO public."Artists" VALUES (17, 'HEALTH', 1, 'Исполнитель HEALTH известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb5b2bf033db0073228084edb4', 2000, 2025);
INSERT INTO public."Artists" VALUES (18, 'Spor', 1, 'Исполнитель Spor известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb3200487ca708d8587c557783', 2000, 2025);
INSERT INTO public."Artists" VALUES (19, 'Toronto Is Broken', 1, 'Исполнитель Toronto Is Broken известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebd7e5abc71f1fec13033a5baa', 2000, 2025);
INSERT INTO public."Artists" VALUES (20, 'WesGhost', 1, 'Исполнитель WesGhost известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb09935a526cc02e86cc127b5e', 2000, 2025);
INSERT INTO public."Artists" VALUES (21, 'GG Magree', 1, 'Исполнитель GG Magree известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebf784e061371be04d98b542e5', 2000, 2025);
INSERT INTO public."Artists" VALUES (22, 'RIOT', 1, 'Исполнитель RIOT известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebd459730d3fb832bc9e18113e', 2000, 2025);
INSERT INTO public."Artists" VALUES (23, 'Dr. Nakano', 1, 'Исполнитель Dr. Nakano известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebf243cce1a787d3f6a84397f6', 2000, 2025);
INSERT INTO public."Artists" VALUES (24, 'Koven', 1, 'Исполнитель Koven известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb558339d8bae95cd33a20c4c7', 2000, 2025);
INSERT INTO public."Artists" VALUES (25, 'Magnetude', 1, 'Исполнитель Magnetude известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebfca737f35ace839fea98adcc', 2000, 2025);
INSERT INTO public."Artists" VALUES (26, 'Skyth', 1, 'Исполнитель Skyth известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb9c0ccd821d055f7670190408', 2000, 2025);
INSERT INTO public."Artists" VALUES (27, '仮想夢プラザ', 1, 'Исполнитель 仮想夢プラザ известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebbea822341ca18435964b3a22', 2000, 2025);
INSERT INTO public."Artists" VALUES (28, 'Hybrid', 1, 'Исполнитель Hybrid известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb2d875cc2e54d7270f8d05f7e', 2000, 2025);
INSERT INTO public."Artists" VALUES (29, 'REEBZ', 1, 'Исполнитель REEBZ известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebe1ddd40d74ec59697d1ea2b9', 2000, 2025);
INSERT INTO public."Artists" VALUES (30, 'Zardonic', 1, 'Исполнитель Zardonic известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebf2112a8bed841437334d935b', 2000, 2025);
INSERT INTO public."Artists" VALUES (31, 'Geoffplaysguitar', 1, 'Исполнитель Geoffplaysguitar известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebc80b2654f9c8ff1eeac4a1cd', 2000, 2025);
INSERT INTO public."Artists" VALUES (32, 'Юлия Коган', 1, 'Исполнитель Юлия Коган известен своими треками на Spotify.', 'https://i.scdn.co/image/ab67616d0000b27359c1339003364d093ead463f', 2000, 2025);
INSERT INTO public."Artists" VALUES (33, 'frenetic virtual orchestra', 1, 'Исполнитель frenetic virtual orchestra известен своими треками на Spotify.', 'https://i.scdn.co/image/ab67616d0000b273caf25a695ad72d5fa1641d01', 2000, 2025);
INSERT INTO public."Artists" VALUES (34, 'UNKLE', 1, 'Исполнитель UNKLE известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebac89f1cb4f6881854f55f761', 2000, 2025);
INSERT INTO public."Artists" VALUES (35, 'Atomic Heart', 1, 'Исполнитель Atomic Heart известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb5b9d4a3ca752b33bf6d8a690', 2000, 2025);
INSERT INTO public."Artists" VALUES (36, 'Habstrakt', 1, 'Исполнитель Habstrakt известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebd4f9e0206342d45ab98840c2', 2000, 2025);
INSERT INTO public."Artists" VALUES (37, 'Matthew K. Heafy', 1, 'Исполнитель Matthew K. Heafy известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb1d878a14af100015aae655c2', 2000, 2025);
INSERT INTO public."Artists" VALUES (38, 'Nedaj', 1, 'Исполнитель Nedaj известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb11586ee95f9e07f47252d1f6', 2000, 2025);
INSERT INTO public."Artists" VALUES (39, 'Kayzo', 1, 'Исполнитель Kayzo известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb5e72708b64f379843417ddee', 2000, 2025);
INSERT INTO public."Artists" VALUES (40, 'Skrillex', 1, 'Исполнитель Skrillex известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5ebe32002317387b6d659308a94', 2000, 2025);
INSERT INTO public."Artists" VALUES (41, 'ISOxo', 1, 'Исполнитель ISOxo известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb69dea5e9c932833f17b7ddce', 2000, 2025);
INSERT INTO public."Artists" VALUES (42, 'Cynthoni', 1, 'Исполнитель Cynthoni известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb068c68cd72c01daf38873103', 2000, 2025);
INSERT INTO public."Artists" VALUES (43, 'Sewerslvt', 1, 'Исполнитель Sewerslvt известен своими треками на Spotify.', 'https://i.scdn.co/image/ab6761610000e5eb8a1271f7f32e5202924ebff2', 2000, 2025);


--
-- TOC entry 3515 (class 0 OID 17303)
-- Dependencies: 243
-- Data for Name: ArtistsTracks; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ArtistsTracks" VALUES (1, 46);
INSERT INTO public."ArtistsTracks" VALUES (1, 33);
INSERT INTO public."ArtistsTracks" VALUES (1, 2);
INSERT INTO public."ArtistsTracks" VALUES (2, 20);
INSERT INTO public."ArtistsTracks" VALUES (2, 17);
INSERT INTO public."ArtistsTracks" VALUES (2, 1);
INSERT INTO public."ArtistsTracks" VALUES (3, 39);
INSERT INTO public."ArtistsTracks" VALUES (4, 30);
INSERT INTO public."ArtistsTracks" VALUES (5, 27);
INSERT INTO public."ArtistsTracks" VALUES (6, 21);
INSERT INTO public."ArtistsTracks" VALUES (7, 35);
INSERT INTO public."ArtistsTracks" VALUES (7, 14);
INSERT INTO public."ArtistsTracks" VALUES (8, 14);
INSERT INTO public."ArtistsTracks" VALUES (9, 28);
INSERT INTO public."ArtistsTracks" VALUES (10, 7);
INSERT INTO public."ArtistsTracks" VALUES (11, 37);
INSERT INTO public."ArtistsTracks" VALUES (11, 32);
INSERT INTO public."ArtistsTracks" VALUES (11, 25);
INSERT INTO public."ArtistsTracks" VALUES (11, 4);
INSERT INTO public."ArtistsTracks" VALUES (12, 45);
INSERT INTO public."ArtistsTracks" VALUES (12, 42);
INSERT INTO public."ArtistsTracks" VALUES (12, 40);
INSERT INTO public."ArtistsTracks" VALUES (12, 23);
INSERT INTO public."ArtistsTracks" VALUES (12, 8);
INSERT INTO public."ArtistsTracks" VALUES (13, 10);
INSERT INTO public."ArtistsTracks" VALUES (14, 10);
INSERT INTO public."ArtistsTracks" VALUES (15, 28);
INSERT INTO public."ArtistsTracks" VALUES (16, 3);
INSERT INTO public."ArtistsTracks" VALUES (17, 38);
INSERT INTO public."ArtistsTracks" VALUES (18, 27);
INSERT INTO public."ArtistsTracks" VALUES (19, 46);
INSERT INTO public."ArtistsTracks" VALUES (19, 39);
INSERT INTO public."ArtistsTracks" VALUES (19, 33);
INSERT INTO public."ArtistsTracks" VALUES (19, 15);
INSERT INTO public."ArtistsTracks" VALUES (19, 2);
INSERT INTO public."ArtistsTracks" VALUES (20, 19);
INSERT INTO public."ArtistsTracks" VALUES (21, 31);
INSERT INTO public."ArtistsTracks" VALUES (22, 43);
INSERT INTO public."ArtistsTracks" VALUES (22, 34);
INSERT INTO public."ArtistsTracks" VALUES (23, 21);
INSERT INTO public."ArtistsTracks" VALUES (24, 24);
INSERT INTO public."ArtistsTracks" VALUES (25, 36);
INSERT INTO public."ArtistsTracks" VALUES (25, 22);
INSERT INTO public."ArtistsTracks" VALUES (25, 5);
INSERT INTO public."ArtistsTracks" VALUES (26, 35);
INSERT INTO public."ArtistsTracks" VALUES (27, 18);
INSERT INTO public."ArtistsTracks" VALUES (28, 16);
INSERT INTO public."ArtistsTracks" VALUES (28, 11);
INSERT INTO public."ArtistsTracks" VALUES (28, 6);
INSERT INTO public."ArtistsTracks" VALUES (29, 33);
INSERT INTO public."ArtistsTracks" VALUES (29, 15);
INSERT INTO public."ArtistsTracks" VALUES (29, 2);
INSERT INTO public."ArtistsTracks" VALUES (30, 39);
INSERT INTO public."ArtistsTracks" VALUES (31, 13);
INSERT INTO public."ArtistsTracks" VALUES (32, 13);
INSERT INTO public."ArtistsTracks" VALUES (33, 13);
INSERT INTO public."ArtistsTracks" VALUES (34, 9);
INSERT INTO public."ArtistsTracks" VALUES (35, 13);
INSERT INTO public."ArtistsTracks" VALUES (36, 12);
INSERT INTO public."ArtistsTracks" VALUES (37, 28);
INSERT INTO public."ArtistsTracks" VALUES (38, 44);
INSERT INTO public."ArtistsTracks" VALUES (39, 26);
INSERT INTO public."ArtistsTracks" VALUES (39, 19);
INSERT INTO public."ArtistsTracks" VALUES (40, 29);
INSERT INTO public."ArtistsTracks" VALUES (41, 29);
INSERT INTO public."ArtistsTracks" VALUES (42, 41);
INSERT INTO public."ArtistsTracks" VALUES (43, 41);


--
-- TOC entry 3514 (class 0 OID 17261)
-- Dependencies: 242
-- Data for Name: Countryes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Countryes" VALUES (1, 'Unknown');


--
-- TOC entry 3492 (class 0 OID 17050)
-- Dependencies: 220
-- Data for Name: Genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Genres" VALUES (1, 'alternative dance');
INSERT INTO public."Genres" VALUES (2, 'alternative metal');
INSERT INTO public."Genres" VALUES (3, 'ambient');
INSERT INTO public."Genres" VALUES (4, 'bass house');
INSERT INTO public."Genres" VALUES (5, 'bassline');
INSERT INTO public."Genres" VALUES (6, 'big beat');
INSERT INTO public."Genres" VALUES (7, 'breakbeat');
INSERT INTO public."Genres" VALUES (8, 'breakcore');
INSERT INTO public."Genres" VALUES (9, 'chillstep');
INSERT INTO public."Genres" VALUES (10, 'chillwave');
INSERT INTO public."Genres" VALUES (11, 'deathstep');
INSERT INTO public."Genres" VALUES (12, 'downtempo');
INSERT INTO public."Genres" VALUES (13, 'drone');
INSERT INTO public."Genres" VALUES (14, 'drum and bass');
INSERT INTO public."Genres" VALUES (15, 'drumstep');
INSERT INTO public."Genres" VALUES (16, 'dubstep');
INSERT INTO public."Genres" VALUES (17, 'ebm');
INSERT INTO public."Genres" VALUES (18, 'edm');
INSERT INTO public."Genres" VALUES (19, 'electro');
INSERT INTO public."Genres" VALUES (20, 'electroclash');
INSERT INTO public."Genres" VALUES (21, 'electronic');
INSERT INTO public."Genres" VALUES (22, 'electronica');
INSERT INTO public."Genres" VALUES (23, 'future bass');
INSERT INTO public."Genres" VALUES (24, 'g-house');
INSERT INTO public."Genres" VALUES (25, 'hardcore techno');
INSERT INTO public."Genres" VALUES (26, 'idm');
INSERT INTO public."Genres" VALUES (27, 'industrial');
INSERT INTO public."Genres" VALUES (28, 'industrial metal');
INSERT INTO public."Genres" VALUES (29, 'industrial rock');
INSERT INTO public."Genres" VALUES (30, 'jungle');
INSERT INTO public."Genres" VALUES (31, 'liquid funk');
INSERT INTO public."Genres" VALUES (32, 'lo-fi house');
INSERT INTO public."Genres" VALUES (33, 'melodic bass');
INSERT INTO public."Genres" VALUES (34, 'noise rock');
INSERT INTO public."Genres" VALUES (35, 'nu metal');
INSERT INTO public."Genres" VALUES (36, 'riddim');
INSERT INTO public."Genres" VALUES (37, 'speedcore');
INSERT INTO public."Genres" VALUES (38, 'synthpop');
INSERT INTO public."Genres" VALUES (39, 'trip hop');
INSERT INTO public."Genres" VALUES (40, 'vaporwave');
INSERT INTO public."Genres" VALUES (41, 'witch house');


--
-- TOC entry 3511 (class 0 OID 17224)
-- Dependencies: 239
-- Data for Name: GenresAlbums; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."GenresAlbums" VALUES (29, 12);
INSERT INTO public."GenresAlbums" VALUES (16, 10);
INSERT INTO public."GenresAlbums" VALUES (2, 18);
INSERT INTO public."GenresAlbums" VALUES (35, 12);
INSERT INTO public."GenresAlbums" VALUES (40, 1);
INSERT INTO public."GenresAlbums" VALUES (16, 6);
INSERT INTO public."GenresAlbums" VALUES (28, 20);
INSERT INTO public."GenresAlbums" VALUES (23, 7);
INSERT INTO public."GenresAlbums" VALUES (27, 26);
INSERT INTO public."GenresAlbums" VALUES (29, 26);
INSERT INTO public."GenresAlbums" VALUES (14, 21);
INSERT INTO public."GenresAlbums" VALUES (16, 16);
INSERT INTO public."GenresAlbums" VALUES (31, 35);
INSERT INTO public."GenresAlbums" VALUES (17, 13);
INSERT INTO public."GenresAlbums" VALUES (28, 11);
INSERT INTO public."GenresAlbums" VALUES (31, 32);
INSERT INTO public."GenresAlbums" VALUES (39, 24);
INSERT INTO public."GenresAlbums" VALUES (3, 1);
INSERT INTO public."GenresAlbums" VALUES (26, 15);
INSERT INTO public."GenresAlbums" VALUES (17, 22);
INSERT INTO public."GenresAlbums" VALUES (16, 7);
INSERT INTO public."GenresAlbums" VALUES (29, 11);
INSERT INTO public."GenresAlbums" VALUES (36, 4);
INSERT INTO public."GenresAlbums" VALUES (11, 23);
INSERT INTO public."GenresAlbums" VALUES (27, 12);
INSERT INTO public."GenresAlbums" VALUES (14, 17);
INSERT INTO public."GenresAlbums" VALUES (7, 25);
INSERT INTO public."GenresAlbums" VALUES (28, 18);
INSERT INTO public."GenresAlbums" VALUES (38, 42);
INSERT INTO public."GenresAlbums" VALUES (15, 40);
INSERT INTO public."GenresAlbums" VALUES (16, 28);
INSERT INTO public."GenresAlbums" VALUES (36, 6);
INSERT INTO public."GenresAlbums" VALUES (14, 2);
INSERT INTO public."GenresAlbums" VALUES (16, 4);
INSERT INTO public."GenresAlbums" VALUES (8, 37);
INSERT INTO public."GenresAlbums" VALUES (41, 26);
INSERT INTO public."GenresAlbums" VALUES (6, 25);
INSERT INTO public."GenresAlbums" VALUES (15, 33);
INSERT INTO public."GenresAlbums" VALUES (27, 20);
INSERT INTO public."GenresAlbums" VALUES (6, 14);
INSERT INTO public."GenresAlbums" VALUES (39, 13);
INSERT INTO public."GenresAlbums" VALUES (37, 17);
INSERT INTO public."GenresAlbums" VALUES (18, 10);
INSERT INTO public."GenresAlbums" VALUES (40, 27);
INSERT INTO public."GenresAlbums" VALUES (25, 14);
INSERT INTO public."GenresAlbums" VALUES (22, 31);
INSERT INTO public."GenresAlbums" VALUES (11, 6);
INSERT INTO public."GenresAlbums" VALUES (15, 21);
INSERT INTO public."GenresAlbums" VALUES (14, 35);
INSERT INTO public."GenresAlbums" VALUES (16, 23);
INSERT INTO public."GenresAlbums" VALUES (28, 12);
INSERT INTO public."GenresAlbums" VALUES (6, 39);
INSERT INTO public."GenresAlbums" VALUES (13, 1);
INSERT INTO public."GenresAlbums" VALUES (18, 16);
INSERT INTO public."GenresAlbums" VALUES (7, 41);
INSERT INTO public."GenresAlbums" VALUES (17, 38);
INSERT INTO public."GenresAlbums" VALUES (4, 28);
INSERT INTO public."GenresAlbums" VALUES (1, 42);
INSERT INTO public."GenresAlbums" VALUES (11, 10);
INSERT INTO public."GenresAlbums" VALUES (7, 17);
INSERT INTO public."GenresAlbums" VALUES (36, 10);
INSERT INTO public."GenresAlbums" VALUES (2, 12);
INSERT INTO public."GenresAlbums" VALUES (12, 24);
INSERT INTO public."GenresAlbums" VALUES (39, 22);
INSERT INTO public."GenresAlbums" VALUES (14, 40);
INSERT INTO public."GenresAlbums" VALUES (37, 37);
INSERT INTO public."GenresAlbums" VALUES (22, 8);
INSERT INTO public."GenresAlbums" VALUES (6, 31);
INSERT INTO public."GenresAlbums" VALUES (21, 16);
INSERT INTO public."GenresAlbums" VALUES (14, 33);
INSERT INTO public."GenresAlbums" VALUES (27, 18);
INSERT INTO public."GenresAlbums" VALUES (31, 36);
INSERT INTO public."GenresAlbums" VALUES (30, 17);
INSERT INTO public."GenresAlbums" VALUES (31, 2);
INSERT INTO public."GenresAlbums" VALUES (10, 27);
INSERT INTO public."GenresAlbums" VALUES (27, 13);
INSERT INTO public."GenresAlbums" VALUES (14, 34);
INSERT INTO public."GenresAlbums" VALUES (27, 11);
INSERT INTO public."GenresAlbums" VALUES (39, 38);
INSERT INTO public."GenresAlbums" VALUES (15, 34);
INSERT INTO public."GenresAlbums" VALUES (14, 32);
INSERT INTO public."GenresAlbums" VALUES (28, 26);
INSERT INTO public."GenresAlbums" VALUES (30, 37);
INSERT INTO public."GenresAlbums" VALUES (14, 36);
INSERT INTO public."GenresAlbums" VALUES (35, 20);
INSERT INTO public."GenresAlbums" VALUES (6, 41);
INSERT INTO public."GenresAlbums" VALUES (11, 4);
INSERT INTO public."GenresAlbums" VALUES (7, 14);
INSERT INTO public."GenresAlbums" VALUES (27, 22);
INSERT INTO public."GenresAlbums" VALUES (7, 39);
INSERT INTO public."GenresAlbums" VALUES (27, 38);
INSERT INTO public."GenresAlbums" VALUES (9, 40);
INSERT INTO public."GenresAlbums" VALUES (33, 3);
INSERT INTO public."GenresAlbums" VALUES (34, 26);
INSERT INTO public."GenresAlbums" VALUES (6, 8);
INSERT INTO public."GenresAlbums" VALUES (19, 16);
INSERT INTO public."GenresAlbums" VALUES (35, 11);
INSERT INTO public."GenresAlbums" VALUES (2, 20);
INSERT INTO public."GenresAlbums" VALUES (24, 28);
INSERT INTO public."GenresAlbums" VALUES (8, 17);
INSERT INTO public."GenresAlbums" VALUES (29, 18);
INSERT INTO public."GenresAlbums" VALUES (31, 40);
INSERT INTO public."GenresAlbums" VALUES (20, 42);
INSERT INTO public."GenresAlbums" VALUES (29, 20);
INSERT INTO public."GenresAlbums" VALUES (32, 19);
INSERT INTO public."GenresAlbums" VALUES (35, 18);
INSERT INTO public."GenresAlbums" VALUES (36, 23);
INSERT INTO public."GenresAlbums" VALUES (18, 23);
INSERT INTO public."GenresAlbums" VALUES (8, 30);
INSERT INTO public."GenresAlbums" VALUES (5, 28);


--
-- TOC entry 3510 (class 0 OID 17188)
-- Dependencies: 238
-- Data for Name: GenresArtists; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."GenresArtists" VALUES (1, 10);
INSERT INTO public."GenresArtists" VALUES (2, 12);
INSERT INTO public."GenresArtists" VALUES (3, 27);
INSERT INTO public."GenresArtists" VALUES (4, 41);
INSERT INTO public."GenresArtists" VALUES (4, 36);
INSERT INTO public."GenresArtists" VALUES (5, 36);
INSERT INTO public."GenresArtists" VALUES (6, 28);
INSERT INTO public."GenresArtists" VALUES (6, 11);
INSERT INTO public."GenresArtists" VALUES (6, 5);
INSERT INTO public."GenresArtists" VALUES (7, 38);
INSERT INTO public."GenresArtists" VALUES (7, 28);
INSERT INTO public."GenresArtists" VALUES (7, 5);
INSERT INTO public."GenresArtists" VALUES (8, 43);
INSERT INTO public."GenresArtists" VALUES (8, 42);
INSERT INTO public."GenresArtists" VALUES (8, 38);
INSERT INTO public."GenresArtists" VALUES (8, 4);
INSERT INTO public."GenresArtists" VALUES (9, 24);
INSERT INTO public."GenresArtists" VALUES (9, 18);
INSERT INTO public."GenresArtists" VALUES (10, 6);
INSERT INTO public."GenresArtists" VALUES (11, 39);
INSERT INTO public."GenresArtists" VALUES (11, 30);
INSERT INTO public."GenresArtists" VALUES (11, 22);
INSERT INTO public."GenresArtists" VALUES (12, 34);
INSERT INTO public."GenresArtists" VALUES (13, 27);
INSERT INTO public."GenresArtists" VALUES (14, 38);
INSERT INTO public."GenresArtists" VALUES (14, 30);
INSERT INTO public."GenresArtists" VALUES (14, 29);
INSERT INTO public."GenresArtists" VALUES (14, 25);
INSERT INTO public."GenresArtists" VALUES (14, 24);
INSERT INTO public."GenresArtists" VALUES (14, 19);
INSERT INTO public."GenresArtists" VALUES (14, 18);
INSERT INTO public."GenresArtists" VALUES (14, 1);
INSERT INTO public."GenresArtists" VALUES (15, 25);
INSERT INTO public."GenresArtists" VALUES (15, 24);
INSERT INTO public."GenresArtists" VALUES (15, 18);
INSERT INTO public."GenresArtists" VALUES (16, 40);
INSERT INTO public."GenresArtists" VALUES (16, 39);
INSERT INTO public."GenresArtists" VALUES (16, 36);
INSERT INTO public."GenresArtists" VALUES (16, 22);
INSERT INTO public."GenresArtists" VALUES (16, 21);
INSERT INTO public."GenresArtists" VALUES (16, 18);
INSERT INTO public."GenresArtists" VALUES (16, 7);
INSERT INTO public."GenresArtists" VALUES (17, 2);
INSERT INTO public."GenresArtists" VALUES (18, 41);
INSERT INTO public."GenresArtists" VALUES (18, 40);
INSERT INTO public."GenresArtists" VALUES (18, 39);
INSERT INTO public."GenresArtists" VALUES (19, 40);
INSERT INTO public."GenresArtists" VALUES (20, 10);
INSERT INTO public."GenresArtists" VALUES (21, 40);
INSERT INTO public."GenresArtists" VALUES (22, 11);
INSERT INTO public."GenresArtists" VALUES (23, 21);
INSERT INTO public."GenresArtists" VALUES (24, 36);
INSERT INTO public."GenresArtists" VALUES (25, 5);
INSERT INTO public."GenresArtists" VALUES (26, 14);
INSERT INTO public."GenresArtists" VALUES (27, 30);
INSERT INTO public."GenresArtists" VALUES (27, 17);
INSERT INTO public."GenresArtists" VALUES (27, 12);
INSERT INTO public."GenresArtists" VALUES (27, 2);
INSERT INTO public."GenresArtists" VALUES (28, 30);
INSERT INTO public."GenresArtists" VALUES (28, 17);
INSERT INTO public."GenresArtists" VALUES (28, 12);
INSERT INTO public."GenresArtists" VALUES (29, 17);
INSERT INTO public."GenresArtists" VALUES (29, 12);
INSERT INTO public."GenresArtists" VALUES (30, 43);
INSERT INTO public."GenresArtists" VALUES (30, 42);
INSERT INTO public."GenresArtists" VALUES (30, 38);
INSERT INTO public."GenresArtists" VALUES (30, 18);
INSERT INTO public."GenresArtists" VALUES (31, 24);
INSERT INTO public."GenresArtists" VALUES (31, 19);
INSERT INTO public."GenresArtists" VALUES (32, 16);
INSERT INTO public."GenresArtists" VALUES (33, 8);
INSERT INTO public."GenresArtists" VALUES (34, 17);
INSERT INTO public."GenresArtists" VALUES (35, 12);
INSERT INTO public."GenresArtists" VALUES (36, 39);
INSERT INTO public."GenresArtists" VALUES (36, 22);
INSERT INTO public."GenresArtists" VALUES (37, 43);
INSERT INTO public."GenresArtists" VALUES (37, 42);
INSERT INTO public."GenresArtists" VALUES (37, 38);
INSERT INTO public."GenresArtists" VALUES (38, 10);
INSERT INTO public."GenresArtists" VALUES (39, 34);
INSERT INTO public."GenresArtists" VALUES (39, 2);
INSERT INTO public."GenresArtists" VALUES (40, 27);
INSERT INTO public."GenresArtists" VALUES (40, 23);
INSERT INTO public."GenresArtists" VALUES (40, 6);
INSERT INTO public."GenresArtists" VALUES (41, 17);
INSERT INTO public."GenresArtists" VALUES (41, 13);


--
-- TOC entry 3512 (class 0 OID 17239)
-- Dependencies: 240
-- Data for Name: GenresTracks; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."GenresTracks" VALUES (1, 7);
INSERT INTO public."GenresTracks" VALUES (2, 45);
INSERT INTO public."GenresTracks" VALUES (2, 42);
INSERT INTO public."GenresTracks" VALUES (2, 40);
INSERT INTO public."GenresTracks" VALUES (2, 23);
INSERT INTO public."GenresTracks" VALUES (2, 8);
INSERT INTO public."GenresTracks" VALUES (3, 18);
INSERT INTO public."GenresTracks" VALUES (4, 12);
INSERT INTO public."GenresTracks" VALUES (5, 12);
INSERT INTO public."GenresTracks" VALUES (6, 37);
INSERT INTO public."GenresTracks" VALUES (6, 32);
INSERT INTO public."GenresTracks" VALUES (6, 27);
INSERT INTO public."GenresTracks" VALUES (6, 25);
INSERT INTO public."GenresTracks" VALUES (6, 16);
INSERT INTO public."GenresTracks" VALUES (6, 11);
INSERT INTO public."GenresTracks" VALUES (6, 6);
INSERT INTO public."GenresTracks" VALUES (6, 4);
INSERT INTO public."GenresTracks" VALUES (7, 44);
INSERT INTO public."GenresTracks" VALUES (7, 27);
INSERT INTO public."GenresTracks" VALUES (7, 16);
INSERT INTO public."GenresTracks" VALUES (7, 11);
INSERT INTO public."GenresTracks" VALUES (7, 6);
INSERT INTO public."GenresTracks" VALUES (8, 44);
INSERT INTO public."GenresTracks" VALUES (8, 41);
INSERT INTO public."GenresTracks" VALUES (8, 30);
INSERT INTO public."GenresTracks" VALUES (9, 24);
INSERT INTO public."GenresTracks" VALUES (10, 21);
INSERT INTO public."GenresTracks" VALUES (11, 43);
INSERT INTO public."GenresTracks" VALUES (11, 34);
INSERT INTO public."GenresTracks" VALUES (11, 26);
INSERT INTO public."GenresTracks" VALUES (11, 19);
INSERT INTO public."GenresTracks" VALUES (12, 9);
INSERT INTO public."GenresTracks" VALUES (13, 18);
INSERT INTO public."GenresTracks" VALUES (14, 46);
INSERT INTO public."GenresTracks" VALUES (14, 44);
INSERT INTO public."GenresTracks" VALUES (14, 36);
INSERT INTO public."GenresTracks" VALUES (14, 33);
INSERT INTO public."GenresTracks" VALUES (14, 24);
INSERT INTO public."GenresTracks" VALUES (14, 22);
INSERT INTO public."GenresTracks" VALUES (14, 15);
INSERT INTO public."GenresTracks" VALUES (14, 5);
INSERT INTO public."GenresTracks" VALUES (14, 2);
INSERT INTO public."GenresTracks" VALUES (15, 36);
INSERT INTO public."GenresTracks" VALUES (15, 24);
INSERT INTO public."GenresTracks" VALUES (15, 22);
INSERT INTO public."GenresTracks" VALUES (15, 5);
INSERT INTO public."GenresTracks" VALUES (16, 43);
INSERT INTO public."GenresTracks" VALUES (16, 34);
INSERT INTO public."GenresTracks" VALUES (16, 31);
INSERT INTO public."GenresTracks" VALUES (16, 29);
INSERT INTO public."GenresTracks" VALUES (16, 26);
INSERT INTO public."GenresTracks" VALUES (16, 19);
INSERT INTO public."GenresTracks" VALUES (16, 12);
INSERT INTO public."GenresTracks" VALUES (17, 20);
INSERT INTO public."GenresTracks" VALUES (17, 17);
INSERT INTO public."GenresTracks" VALUES (17, 1);
INSERT INTO public."GenresTracks" VALUES (18, 29);
INSERT INTO public."GenresTracks" VALUES (18, 26);
INSERT INTO public."GenresTracks" VALUES (18, 19);
INSERT INTO public."GenresTracks" VALUES (19, 29);
INSERT INTO public."GenresTracks" VALUES (20, 7);
INSERT INTO public."GenresTracks" VALUES (21, 29);
INSERT INTO public."GenresTracks" VALUES (22, 37);
INSERT INTO public."GenresTracks" VALUES (22, 32);
INSERT INTO public."GenresTracks" VALUES (22, 25);
INSERT INTO public."GenresTracks" VALUES (22, 4);
INSERT INTO public."GenresTracks" VALUES (23, 31);
INSERT INTO public."GenresTracks" VALUES (24, 12);
INSERT INTO public."GenresTracks" VALUES (25, 27);
INSERT INTO public."GenresTracks" VALUES (26, 10);
INSERT INTO public."GenresTracks" VALUES (27, 45);
INSERT INTO public."GenresTracks" VALUES (27, 42);
INSERT INTO public."GenresTracks" VALUES (27, 40);
INSERT INTO public."GenresTracks" VALUES (27, 38);
INSERT INTO public."GenresTracks" VALUES (27, 23);
INSERT INTO public."GenresTracks" VALUES (27, 20);
INSERT INTO public."GenresTracks" VALUES (27, 17);
INSERT INTO public."GenresTracks" VALUES (27, 8);
INSERT INTO public."GenresTracks" VALUES (27, 1);
INSERT INTO public."GenresTracks" VALUES (28, 45);
INSERT INTO public."GenresTracks" VALUES (28, 42);
INSERT INTO public."GenresTracks" VALUES (28, 40);
INSERT INTO public."GenresTracks" VALUES (28, 38);
INSERT INTO public."GenresTracks" VALUES (28, 23);
INSERT INTO public."GenresTracks" VALUES (28, 8);
INSERT INTO public."GenresTracks" VALUES (29, 45);
INSERT INTO public."GenresTracks" VALUES (29, 42);
INSERT INTO public."GenresTracks" VALUES (29, 40);
INSERT INTO public."GenresTracks" VALUES (29, 38);
INSERT INTO public."GenresTracks" VALUES (29, 23);
INSERT INTO public."GenresTracks" VALUES (29, 8);
INSERT INTO public."GenresTracks" VALUES (30, 44);
INSERT INTO public."GenresTracks" VALUES (30, 41);
INSERT INTO public."GenresTracks" VALUES (31, 46);
INSERT INTO public."GenresTracks" VALUES (31, 33);
INSERT INTO public."GenresTracks" VALUES (31, 24);
INSERT INTO public."GenresTracks" VALUES (31, 15);
INSERT INTO public."GenresTracks" VALUES (31, 2);
INSERT INTO public."GenresTracks" VALUES (32, 3);
INSERT INTO public."GenresTracks" VALUES (33, 14);
INSERT INTO public."GenresTracks" VALUES (34, 38);
INSERT INTO public."GenresTracks" VALUES (35, 45);
INSERT INTO public."GenresTracks" VALUES (35, 42);
INSERT INTO public."GenresTracks" VALUES (35, 40);
INSERT INTO public."GenresTracks" VALUES (35, 23);
INSERT INTO public."GenresTracks" VALUES (35, 8);
INSERT INTO public."GenresTracks" VALUES (36, 43);
INSERT INTO public."GenresTracks" VALUES (36, 34);
INSERT INTO public."GenresTracks" VALUES (36, 26);
INSERT INTO public."GenresTracks" VALUES (36, 19);
INSERT INTO public."GenresTracks" VALUES (37, 44);
INSERT INTO public."GenresTracks" VALUES (37, 41);
INSERT INTO public."GenresTracks" VALUES (38, 7);
INSERT INTO public."GenresTracks" VALUES (39, 20);
INSERT INTO public."GenresTracks" VALUES (39, 17);
INSERT INTO public."GenresTracks" VALUES (39, 9);
INSERT INTO public."GenresTracks" VALUES (39, 1);
INSERT INTO public."GenresTracks" VALUES (40, 21);
INSERT INTO public."GenresTracks" VALUES (40, 18);
INSERT INTO public."GenresTracks" VALUES (41, 38);


--
-- TOC entry 3504 (class 0 OID 17108)
-- Dependencies: 232
-- Data for Name: Playlists; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Playlists" VALUES (1, 'Best of 2025', 1, '2025-05-08', 85456, NULL);
INSERT INTO public."Playlists" VALUES (2, 'Means A Lot To Me', 4, '2024-10-20', 4863, NULL);
INSERT INTO public."Playlists" VALUES (3, 'Death Notices Full OST', 9, '2023-10-29', 81189, NULL);


--
-- TOC entry 3507 (class 0 OID 17128)
-- Dependencies: 235
-- Data for Name: PlaylistsTags; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."PlaylistsTags" VALUES (2, 1);
INSERT INTO public."PlaylistsTags" VALUES (1, 1);
INSERT INTO public."PlaylistsTags" VALUES (3, 2);
INSERT INTO public."PlaylistsTags" VALUES (2, 2);
INSERT INTO public."PlaylistsTags" VALUES (1, 2);
INSERT INTO public."PlaylistsTags" VALUES (1, 3);
INSERT INTO public."PlaylistsTags" VALUES (2, 4);
INSERT INTO public."PlaylistsTags" VALUES (3, 5);
INSERT INTO public."PlaylistsTags" VALUES (3, 6);


--
-- TOC entry 3508 (class 0 OID 17143)
-- Dependencies: 236
-- Data for Name: PlaylistsTracks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3509 (class 0 OID 17158)
-- Dependencies: 237
-- Data for Name: PlaylistsUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."PlaylistsUsers" VALUES (1, 8);
INSERT INTO public."PlaylistsUsers" VALUES (1, 6);
INSERT INTO public."PlaylistsUsers" VALUES (1, 3);
INSERT INTO public."PlaylistsUsers" VALUES (2, 10);
INSERT INTO public."PlaylistsUsers" VALUES (2, 7);
INSERT INTO public."PlaylistsUsers" VALUES (2, 4);
INSERT INTO public."PlaylistsUsers" VALUES (3, 9);
INSERT INTO public."PlaylistsUsers" VALUES (3, 5);
INSERT INTO public."PlaylistsUsers" VALUES (3, 2);
INSERT INTO public."PlaylistsUsers" VALUES (3, 1);


--
-- TOC entry 3494 (class 0 OID 17058)
-- Dependencies: 222
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Roles" VALUES (1, 'Guest');
INSERT INTO public."Roles" VALUES (2, 'Manager');
INSERT INTO public."Roles" VALUES (3, 'User');
INSERT INTO public."Roles" VALUES (4, 'Admin');


--
-- TOC entry 3496 (class 0 OID 17066)
-- Dependencies: 224
-- Data for Name: Subscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Subscriptions" VALUES (1, 'Free');
INSERT INTO public."Subscriptions" VALUES (2, 'Premium');


--
-- TOC entry 3506 (class 0 OID 17121)
-- Dependencies: 234
-- Data for Name: Tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Tags" VALUES (1, 'study');
INSERT INTO public."Tags" VALUES (2, 'chill');
INSERT INTO public."Tags" VALUES (3, 'focus');
INSERT INTO public."Tags" VALUES (4, 'rock');
INSERT INTO public."Tags" VALUES (5, 'workout');
INSERT INTO public."Tags" VALUES (6, 'pop');


--
-- TOC entry 3502 (class 0 OID 17100)
-- Dependencies: 230
-- Data for Name: Tracks; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Tracks" VALUES (1, 'Intruders', '00:11:36', '2007-01-01', 320, 'https://open.spotify.com/track/0zU2OXXBlRj8xIB1mc0jPN', 4.46, 21712928, 22);
INSERT INTO public."Tracks" VALUES (2, 'GOFASTER', '00:04:40', '2025-09-17', 256, 'https://open.spotify.com/track/0WpMAaQq61chei1VkqKGWv', 4.86, 4552008, 35);
INSERT INTO public."Tracks" VALUES (3, 'общедомовой', '00:05:07', '2025-02-14', 320, 'https://open.spotify.com/track/1QVlzjQU2RI4GpVen3x4Ro', 4.77, 17722035, 19);
INSERT INTO public."Tracks" VALUES (4, 'Glam Bucket', '00:05:45', '2007-01-01', 256, 'https://open.spotify.com/track/7k5rnk06tw2kUOj7AQXkha', 3.25, 36747640, 31);
INSERT INTO public."Tracks" VALUES (5, 'The Star', '00:04:57', '2025-05-23', 320, 'https://open.spotify.com/track/4EVYNBO90unYQMUkcgaAqS', 4.05, 80447698, 21);
INSERT INTO public."Tracks" VALUES (6, 'Formula Of Fear', '00:07:07', '2008-09-22', 256, 'https://open.spotify.com/track/0fj2n9wzkojYUy80rOFsLp', 3.17, 97311814, 39);
INSERT INTO public."Tracks" VALUES (7, 'I See Red', '00:03:50', '2025-10-17', 192, 'https://open.spotify.com/track/51WgQlBgMnf1lDxBfZkJsa', 3.91, 79852612, 42);
INSERT INTO public."Tracks" VALUES (8, 'The Big Come Down', '00:04:12', '1999-09-21', 256, 'https://open.spotify.com/track/3cl42VFcRop14wAduvSeaH', 3.4, 80821880, 11);
INSERT INTO public."Tracks" VALUES (9, 'Eye for an Eye', '00:05:45', '2003-01-01', 280, 'https://open.spotify.com/track/6ReswWJnalmGTxyRSTmUkl', 4.64, 65817538, 24);
INSERT INTO public."Tracks" VALUES (10, 'Final Destination', '00:04:50', '2025-02-24', 256, 'https://open.spotify.com/track/7bqSNB1C3tWOUgOQTrODAG', 2.52, 31048640, 15);
INSERT INTO public."Tracks" VALUES (11, 'Orbit', '00:05:25', '2012-09-07', 280, 'https://open.spotify.com/track/1bo3aqhoE0q808wF11ENrC', 4.19, 39317838, 25);
INSERT INTO public."Tracks" VALUES (12, 'Baby', '00:03:56', '2025-02-28', 280, 'https://open.spotify.com/track/1syQiwibqZKAUsgkLn8qtC', 4.94, 42250505, 28);
INSERT INTO public."Tracks" VALUES (13, 'В синем море, в белой пене (Оставайся, мальчик, с нами) [Geoffrey Day Remix]', '00:05:10', '2025-01-29', 280, 'https://open.spotify.com/track/4zW0D21eynN6JcDwGR4f9F', 3.52, 71054588, 29);
INSERT INTO public."Tracks" VALUES (14, 'Obelisk', '00:02:45', '2025-02-27', 256, 'https://open.spotify.com/track/0UCcUFxxlHgaQGojhxzECF', 4.55, 14134899, 3);
INSERT INTO public."Tracks" VALUES (15, 'Breed', '00:03:58', '2023-05-12', 280, 'https://open.spotify.com/track/5cQwBnsRxUhbKDK2C6fR4n', 3.26, 67607976, 32);
INSERT INTO public."Tracks" VALUES (16, 'Siren Of The Storm', '00:09:15', '2025-01-19', 192, 'https://open.spotify.com/track/7HSZ0epFVfoDBFyMjCKMrP', 3.28, 64176479, 41);
INSERT INTO public."Tracks" VALUES (17, 'Freeze', '00:07:28', '1992-01-01', 320, 'https://open.spotify.com/track/7KhV0aeGLhI2G1TC5bpgBe', 3.9, 86513228, 38);
INSERT INTO public."Tracks" VALUES (18, 'あなたを待って', '00:31:34', '2015-05-16', 192, 'https://open.spotify.com/track/3GwYAO8fAxs5k0KiU2hpBP', 3.08, 32425960, 1);
INSERT INTO public."Tracks" VALUES (19, 'Grave', '00:02:39', '2025-01-31', 320, 'https://open.spotify.com/track/3TbzrpJIkSoicguKWNHcSh', 3.01, 77772777, 10);
INSERT INTO public."Tracks" VALUES (20, 'Want', '00:06:09', '2000-03-21', 192, 'https://open.spotify.com/track/6AFz1yXS7boPZlqJd2R7WS', 3.53, 19591519, 13);
INSERT INTO public."Tracks" VALUES (21, 'Ghost City Daze', '00:03:39', '2022-09-02', 280, 'https://open.spotify.com/track/5Npj2l7dvTvICHnh6xwNTU', 3.07, 14408959, 27);
INSERT INTO public."Tracks" VALUES (22, 'Muleta', '00:04:38', '2025-04-11', 192, 'https://open.spotify.com/track/28zBEKDSGAny9y6KrBoCF4', 3.95, 59329189, 34);
INSERT INTO public."Tracks" VALUES (23, 'As Alive As You Need Me To Be', '00:03:53', '2025-07-17', 192, 'https://open.spotify.com/track/1xsEHo7mtGZLEG94vFX11z', 3.55, 71834289, 18);
INSERT INTO public."Tracks" VALUES (24, 'Era', '00:03:17', '2025-04-18', 280, 'https://open.spotify.com/track/1rxxl2R2tU1Uv1oP2bbeUn', 3.99, 54797402, 40);
INSERT INTO public."Tracks" VALUES (25, 'If Rah', '00:07:12', '2016-03-19', 256, 'https://open.spotify.com/track/15j4iuXi1OZfSBKmaVTeN7', 4.93, 33608103, 8);
INSERT INTO public."Tracks" VALUES (26, 'Overload 2K', '00:04:24', '2025-10-24', 192, 'https://open.spotify.com/track/2Y68mc2cWkIwBdqlY04J2e', 4.57, 26952175, 23);
INSERT INTO public."Tracks" VALUES (27, 'Nasty - Spor Remix', '00:05:09', '2015-11-10', 280, 'https://open.spotify.com/track/4SXdAtwtoVCZdUP9mfFFqG', 3.67, 47018173, 14);
INSERT INTO public."Tracks" VALUES (28, 'Dig', '00:03:49', '2025-01-31', 192, 'https://open.spotify.com/track/7nVIE2M0t4sIh3ZkEqrjlY', 3.02, 30268024, 43);
INSERT INTO public."Tracks" VALUES (29, 'Fuze', '00:03:08', '2025-10-24', 256, 'https://open.spotify.com/track/5UZIVxzI4UyrSbg3ZLTGTH', 3.32, 62355472, 16);
INSERT INTO public."Tracks" VALUES (30, 'Undisputed Altitude', '00:11:00', '2025-03-14', 256, 'https://open.spotify.com/track/3K5td8Q9ezKgBjpiiuJDL9', 4.43, 32413023, 30);
INSERT INTO public."Tracks" VALUES (31, 'Run', '00:03:23', '2025-08-13', 256, 'https://open.spotify.com/track/0Ov5YTilb4z4nvuTWeSsUu', 3.16, 42701725, 7);
INSERT INTO public."Tracks" VALUES (32, 'To Heal', '00:02:36', '2007-01-01', 320, 'https://open.spotify.com/track/5K0kPszkKvh6yHEI3wiUCZ', 4.83, 7016621, 31);
INSERT INTO public."Tracks" VALUES (33, 'SOMEWHEREIBELONG', '00:03:47', '2025-05-02', 320, 'https://open.spotify.com/track/2bja1BK8CyrE5U1YLzPWtQ', 3.04, 39633329, 36);
INSERT INTO public."Tracks" VALUES (34, 'March of the Machine', '00:04:07', '2025-08-01', 192, 'https://open.spotify.com/track/2ZhSXdApy452LqJFf7aEwz', 3.7, 60148993, 6);
INSERT INTO public."Tracks" VALUES (35, 'Data Destruction', '00:03:20', '2025-01-30', 320, 'https://open.spotify.com/track/5UM2IIULlGyvYHm4SF3hHI', 3.57, 79887130, 9);
INSERT INTO public."Tracks" VALUES (36, 'Repentance', '00:04:30', '2025-08-01', 280, 'https://open.spotify.com/track/12eQwZCKpzIpccXsH4xQZR', 3.36, 96111491, 33);
INSERT INTO public."Tracks" VALUES (37, 'Beautiful Burnout', '00:08:09', '2007-01-01', 280, 'https://open.spotify.com/track/1I61h0TNyzE86dx1tZzj3b', 3.32, 14678550, 31);
INSERT INTO public."Tracks" VALUES (38, 'ORDINARY LOSS', '00:03:53', '2025-09-11', 192, 'https://open.spotify.com/track/4qUrMbUVDxaMZy2zPB6mD7', 4.46, 3437809, 26);
INSERT INTO public."Tracks" VALUES (39, 'The Masquerade - Zardonic & Toronto Is Broken Remix', '00:04:12', '2025-07-24', 192, 'https://open.spotify.com/track/787izJqCRpk9HOgho07jzb', 4.45, 68700455, 5);
INSERT INTO public."Tracks" VALUES (40, 'Together', '00:10:03', '2020-03-27', 256, 'https://open.spotify.com/track/7iiu6ce9zGfbvs0yBvsZeT', 3.7, 31154483, 20);
INSERT INTO public."Tracks" VALUES (41, 'Lvstlove', '00:06:06', '2025-01-03', 192, 'https://open.spotify.com/track/3INsVctSfXaU6rdPBSPalA', 2.98, 97856870, 37);
INSERT INTO public."Tracks" VALUES (42, 'The Great Below', '00:05:17', '1999-09-21', 280, 'https://open.spotify.com/track/7LBWAib31Cthfz2KoI611Z', 4.56, 91263647, 11);
INSERT INTO public."Tracks" VALUES (43, 'Metalicious', '00:06:00', '2025-06-27', 280, 'https://open.spotify.com/track/2PdmLVo9VOPhlySbMXH6M0', 3.92, 30476401, 4);
INSERT INTO public."Tracks" VALUES (44, 'ONYX', '00:05:12', '2025-04-11', 280, 'https://open.spotify.com/track/0yuIvkFLeSxFBSyyJBiWVV', 4.6, 36864477, 17);
INSERT INTO public."Tracks" VALUES (45, 'At The Heart Of It All', '00:07:14', '1995-01-01', 320, 'https://open.spotify.com/track/4JQEQOu8YKbdtMzVWADAAb', 4.04, 78182712, 12);
INSERT INTO public."Tracks" VALUES (46, 'Circle (feat. Sebotage)', '00:04:07', '2022-03-30', 320, 'https://open.spotify.com/track/2aTXg7Ch2EuKpa7m8Z8GSv', 4.22, 16908411, 2);


--
-- TOC entry 3498 (class 0 OID 17074)
-- Dependencies: 226
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Users" VALUES (1, 'apollinariya.allenova', 'sXFdIl0y', 'Алексей Новожилов', 'aleksey.novojilov@mail.ru', 4, 1, '2025-10-29', '2025-10-29');
INSERT INTO public."Users" VALUES (2, 'leontiy.kozlitin', 'RDJCXFyk', 'Ксения Хуторская', 'kseniya1978@rambler.ru', 3, 1, '2025-08-05', '2025-10-29');
INSERT INTO public."Users" VALUES (3, 'lyudmila.abakumova', 'E3rg2Dct', 'Петр Крылаев', 'petr1968@ya.ru', 3, 1, '2025-10-29', '2025-10-29');
INSERT INTO public."Users" VALUES (4, 'anjela.privalova', 'mZPXkIBf', 'Оксана Добронравова', 'oksana95@ya.ru', 1, 1, '2025-10-29', '2025-10-29');
INSERT INTO public."Users" VALUES (5, 'kseniya1978', 'bCWtEdaB', 'Антонина Пушменкова', 'antonina.pushmenkova@mail.ru', 4, 2, '2025-10-29', '2025-10-29');
INSERT INTO public."Users" VALUES (6, 'oksana95', 'c35tx4ov', 'Людмила Абакумова', 'lyudmila.abakumova@hotmail.com', 3, 2, '2025-09-29', '2025-10-29');
INSERT INTO public."Users" VALUES (7, 'antonina.pushmenkova', 'it3cySf5', 'Ася Шведова', 'asya.vedova@mail.ru', 3, 2, '2025-10-29', '2025-10-29');
INSERT INTO public."Users" VALUES (8, 'asya.vedova', 'z6kkRwhf', 'Аполлинария Алленова', 'apollinariya.allenova@outlook.com', 2, 2, '2025-10-29', '2025-10-29');
INSERT INTO public."Users" VALUES (9, 'aleksey.novojilov', '1XF4kEOq', 'Леонтий Козлитин', 'leontiy.kozlitin@ya.ru', 2, 2, '2025-10-28', '2025-10-29');
INSERT INTO public."Users" VALUES (10, 'petr1968', 'K5PU52zo', 'Анжела Привалова', 'anjela.privalova@rambler.ru', 2, 2, '2025-10-20', '2025-10-29');


--
-- TOC entry 3516 (class 0 OID 17601)
-- Dependencies: 244
-- Data for Name: UsersHistories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."UsersHistories" VALUES (1, 2, '2025-11-27 09:48:22.836636');
INSERT INTO public."UsersHistories" VALUES (2, 2, '2025-11-27 09:51:36.55378');
INSERT INTO public."UsersHistories" VALUES (3, 2, '2025-11-27 10:12:57.556188');
INSERT INTO public."UsersHistories" VALUES (4, 2, '2025-11-27 10:13:15.05561');
INSERT INTO public."UsersHistories" VALUES (5, 2, '2025-11-27 10:21:45.413855');
INSERT INTO public."UsersHistories" VALUES (6, 2, '2025-11-27 10:25:33.95964');
INSERT INTO public."UsersHistories" VALUES (7, 2, '2025-11-27 10:26:04.509328');
INSERT INTO public."UsersHistories" VALUES (8, 2, '2025-11-27 10:26:48.618733');
INSERT INTO public."UsersHistories" VALUES (9, 2, '2025-11-27 10:28:13.879434');
INSERT INTO public."UsersHistories" VALUES (10, 2, '2025-11-27 12:02:04.512665');
INSERT INTO public."UsersHistories" VALUES (11, 2, '2025-11-27 12:03:05.285333');
INSERT INTO public."UsersHistories" VALUES (12, 2, '2025-11-27 12:08:00.693881');
INSERT INTO public."UsersHistories" VALUES (13, 2, '2025-11-27 12:09:02.515216');


--
-- TOC entry 3524 (class 0 OID 0)
-- Dependencies: 227
-- Name: Albums_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Albums_Id_seq"', 43, true);


--
-- TOC entry 3525 (class 0 OID 0)
-- Dependencies: 217
-- Name: ArtistName_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ArtistName_Id_seq"', 43, true);


--
-- TOC entry 3526 (class 0 OID 0)
-- Dependencies: 241
-- Name: Countryes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Countryes_Id_seq"', 1, true);


--
-- TOC entry 3527 (class 0 OID 0)
-- Dependencies: 219
-- Name: Genres_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Genres_Id_seq"', 41, true);


--
-- TOC entry 3528 (class 0 OID 0)
-- Dependencies: 231
-- Name: Playlist_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Playlist_Id_seq"', 3, true);


--
-- TOC entry 3529 (class 0 OID 0)
-- Dependencies: 221
-- Name: Roles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Roles_Id_seq"', 4, true);


--
-- TOC entry 3530 (class 0 OID 0)
-- Dependencies: 223
-- Name: Subscriptions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Subscriptions_Id_seq"', 2, true);


--
-- TOC entry 3531 (class 0 OID 0)
-- Dependencies: 233
-- Name: Tags_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tags_Id_seq"', 1, true);


--
-- TOC entry 3532 (class 0 OID 0)
-- Dependencies: 229
-- Name: Tracks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tracks_Id_seq"', 46, true);


--
-- TOC entry 3533 (class 0 OID 0)
-- Dependencies: 225
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 10, true);


--
-- TOC entry 3298 (class 2606 OID 17098)
-- Name: Albums _Albums__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Albums"
    ADD CONSTRAINT "_Albums__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3288 (class 2606 OID 17048)
-- Name: Artists _ArtistName__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Artists"
    ADD CONSTRAINT "_ArtistName__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3320 (class 2606 OID 17307)
-- Name: ArtistsTracks _ArtistsTracks__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ArtistsTracks"
    ADD CONSTRAINT "_ArtistsTracks__pk" PRIMARY KEY ("ArtistId", "TrackId");


--
-- TOC entry 3318 (class 2606 OID 17267)
-- Name: Countryes _Countryes__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Countryes"
    ADD CONSTRAINT "_Countryes__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3290 (class 2606 OID 17056)
-- Name: Genres _Genre__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Genres"
    ADD CONSTRAINT "_Genre__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3314 (class 2606 OID 17228)
-- Name: GenresAlbums _GenresAlbums__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresAlbums"
    ADD CONSTRAINT "_GenresAlbums__pk" PRIMARY KEY ("GenreId", "AlbumId");


--
-- TOC entry 3312 (class 2606 OID 17192)
-- Name: GenresArtists _GenresArtists__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresArtists"
    ADD CONSTRAINT "_GenresArtists__pk" PRIMARY KEY ("GenreId", "ArtistId");


--
-- TOC entry 3316 (class 2606 OID 17243)
-- Name: GenresTracks _GenresTracks__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresTracks"
    ADD CONSTRAINT "_GenresTracks__pk" PRIMARY KEY ("GenreId", "TrackId");


--
-- TOC entry 3302 (class 2606 OID 17114)
-- Name: Playlists _Playlist__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Playlists"
    ADD CONSTRAINT "_Playlist__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3306 (class 2606 OID 17132)
-- Name: PlaylistsTags _PlaylistsTags__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsTags"
    ADD CONSTRAINT "_PlaylistsTags__pk" PRIMARY KEY ("PlaylistId", "TagId");


--
-- TOC entry 3308 (class 2606 OID 17147)
-- Name: PlaylistsTracks _PlaylistsTracks__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsTracks"
    ADD CONSTRAINT "_PlaylistsTracks__pk" PRIMARY KEY ("PlaylistId", "TrackId");


--
-- TOC entry 3310 (class 2606 OID 17162)
-- Name: PlaylistsUsers _PlaylistsUsers__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsUsers"
    ADD CONSTRAINT "_PlaylistsUsers__pk" PRIMARY KEY ("PlaylistId", "UserId");


--
-- TOC entry 3292 (class 2606 OID 17064)
-- Name: Roles _Roles__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "_Roles__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3294 (class 2606 OID 17072)
-- Name: Subscriptions _Subscriptions__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subscriptions"
    ADD CONSTRAINT "_Subscriptions__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3304 (class 2606 OID 17127)
-- Name: Tags _Tags__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "_Tags__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3300 (class 2606 OID 17106)
-- Name: Tracks _Tracks__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tracks"
    ADD CONSTRAINT "_Tracks__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3296 (class 2606 OID 17080)
-- Name: Users _Users__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "_Users__pk" PRIMARY KEY ("Id");


--
-- TOC entry 3322 (class 2606 OID 17605)
-- Name: UsersHistories userhistory_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UsersHistories"
    ADD CONSTRAINT userhistory_pk PRIMARY KEY ("UserHistoryId");


--
-- TOC entry 3341 (class 2606 OID 17308)
-- Name: ArtistsTracks _ArtistsTracks__Artists_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ArtistsTracks"
    ADD CONSTRAINT "_ArtistsTracks__Artists_FK" FOREIGN KEY ("ArtistId") REFERENCES public."Artists"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3342 (class 2606 OID 17313)
-- Name: ArtistsTracks _ArtistsTracks__Tracks_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ArtistsTracks"
    ADD CONSTRAINT "_ArtistsTracks__Tracks_FK" FOREIGN KEY ("TrackId") REFERENCES public."Tracks"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3337 (class 2606 OID 17229)
-- Name: GenresAlbums _GenresAlbums__Albums_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresAlbums"
    ADD CONSTRAINT "_GenresAlbums__Albums_FK" FOREIGN KEY ("AlbumId") REFERENCES public."Albums"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3338 (class 2606 OID 17234)
-- Name: GenresAlbums _GenresAlbums__Genres_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresAlbums"
    ADD CONSTRAINT "_GenresAlbums__Genres_FK" FOREIGN KEY ("GenreId") REFERENCES public."Genres"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3339 (class 2606 OID 17244)
-- Name: GenresTracks _GenresTracks__Genres_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresTracks"
    ADD CONSTRAINT "_GenresTracks__Genres_FK" FOREIGN KEY ("GenreId") REFERENCES public."Genres"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3340 (class 2606 OID 17249)
-- Name: GenresTracks _GenresTracks__Tracks_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresTracks"
    ADD CONSTRAINT "_GenresTracks__Tracks_FK" FOREIGN KEY ("TrackId") REFERENCES public."Tracks"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3326 (class 2606 OID 17218)
-- Name: Albums albums_artists_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Albums"
    ADD CONSTRAINT albums_artists_fk FOREIGN KEY ("ArtistId") REFERENCES public."Artists"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3323 (class 2606 OID 17268)
-- Name: Artists artists_countryes_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Artists"
    ADD CONSTRAINT artists_countryes_fk FOREIGN KEY ("CountryId") REFERENCES public."Countryes"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3335 (class 2606 OID 17198)
-- Name: GenresArtists genresartists_artists_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresArtists"
    ADD CONSTRAINT genresartists_artists_fk FOREIGN KEY ("ArtistId") REFERENCES public."Artists"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3336 (class 2606 OID 17193)
-- Name: GenresArtists genresartists_genres_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GenresArtists"
    ADD CONSTRAINT genresartists_genres_fk FOREIGN KEY ("GenreId") REFERENCES public."Genres"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3328 (class 2606 OID 17115)
-- Name: Playlists playlist_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Playlists"
    ADD CONSTRAINT playlist_users_fk FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3329 (class 2606 OID 17133)
-- Name: PlaylistsTags playliststags_playlist_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsTags"
    ADD CONSTRAINT playliststags_playlist_fk FOREIGN KEY ("PlaylistId") REFERENCES public."Playlists"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3330 (class 2606 OID 17138)
-- Name: PlaylistsTags playliststags_tags_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsTags"
    ADD CONSTRAINT playliststags_tags_fk FOREIGN KEY ("TagId") REFERENCES public."Tags"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3331 (class 2606 OID 17148)
-- Name: PlaylistsTracks playliststracks_playlist_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsTracks"
    ADD CONSTRAINT playliststracks_playlist_fk FOREIGN KEY ("PlaylistId") REFERENCES public."Playlists"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3332 (class 2606 OID 17153)
-- Name: PlaylistsTracks playliststracks_tracks_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsTracks"
    ADD CONSTRAINT playliststracks_tracks_fk FOREIGN KEY ("TrackId") REFERENCES public."Tracks"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3333 (class 2606 OID 17168)
-- Name: PlaylistsUsers playlistsusers_playlist_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsUsers"
    ADD CONSTRAINT playlistsusers_playlist_fk FOREIGN KEY ("PlaylistId") REFERENCES public."Playlists"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3334 (class 2606 OID 17163)
-- Name: PlaylistsUsers playlistsusers_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistsUsers"
    ADD CONSTRAINT playlistsusers_users_fk FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3327 (class 2606 OID 17273)
-- Name: Tracks tracks_albums_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tracks"
    ADD CONSTRAINT tracks_albums_fk FOREIGN KEY ("AlbumId") REFERENCES public."Albums"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3324 (class 2606 OID 17081)
-- Name: Users users_roles_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_roles_fk FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3325 (class 2606 OID 17086)
-- Name: Users users_subscriptions_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_subscriptions_fk FOREIGN KEY ("SubscriptionId") REFERENCES public."Subscriptions"("Id") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3343 (class 2606 OID 17611)
-- Name: UsersHistories usershistories_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UsersHistories"
    ADD CONSTRAINT usershistories_users_fk FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2025-11-27 16:01:58

--
-- PostgreSQL database dump complete
--

\unrestrict mUNBQdImesV0xucOUHCudfq0ZC5ab7NbSy63B0WSJLzfcHngyV5aX9uTSx4I0fF

